### ISSUE TITLE
Create PostgreSQL example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#104]
Create an example of using tinyhttp with PostgreSQL via [pg-promise](https://github.com/vitaly-t/pg-promise)

If you know a better / more modern PostgreSQL client for Node.js, feel free to suggest them in this thread

app logic can be taken from MongoDB example

**Comment by berto** [comment]
I can help with this. pg-promise sounds good

**Comment by talentlessguy** [comment]
@berto okay, assigning to u

**Comment by talentlessguy** [comment]
Closed via #106
