### ISSUE TITLE
Create React SSR Example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#109]
Create a React SSR example with hydration on the client (e.g. react both on server and client) 

if it is too diffficult to do, then just SSR but PRs with client hydration will be in preference

You can use any abstract layers around SSR, react-ssr for example

React SSR docs: https://reactjs.org/docs/react-dom-server.html

`react-ssr` package: https://www.npmjs.com/package/react-ssr

**Comment by setheal** [comment]
Hey, can I take this issue ?

**Comment by talentlessguy** [comment]
@setheal yup
