### ISSUE TITLE
[middlewares] Add `timestamp` option to logger

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#11]
Would be great if the logger could have an option to print out the timestamp via `timestamp` property.

something like

```ts
app.use(logger({ timestamp: { format: 'MM:SS' } }))
```

and then

```
08:23:12 GET / 200 OK
```

I'm thinking of this option:

```ts
format: string 
```

Probably could be consumed by some date library and then transformed into a timestamp

**Comment by elianiva** [comment]
Would it be good if it also has a response time? Something like `GET / 200 OK - took 250.23ms`. Maybe include this as an option as well and you can choose whether to display the timestamp or this, or both.

**Comment by talentlessguy** [comment]
@elianiva probably would be better to have it as a separate property, so not related to this issue. Gonna make a new one with this prop later.

**Comment by KalebMills** [comment]
`output [unit of time]` is somewhat ambiguous. Are these options attempting to achieve time formatting? If so, would it not be better to pass something like `format: 'HH:MM:SS'`?

**Comment by talentlessguy** [comment]
@KalebMills hm, it is actually a better idea

something like

```ts
app.use(logger({ timestamp: { format: 'HH:MM:SS' }}))
```
`enabled` property, I think now it's not needed. We can just check if `timestamp` is object or Boolean (`true` in this case) and enable it. Otherwise there is no timestamp

**Comment by Arnovsky** [comment]
I would like to take this issue if possible, would adding a dependency (something like `day.js`) for handling formatting of dates be acceptable?

**Comment by talentlessguy** [comment]
@Arnovsky a dependency is fine, and it should be disabled by default, and enabled in case `timestamp` property exists.
