### ISSUE TITLE
Write tests for bot-detector

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#111]
Write tests for `@tinyhttp/bot-detector` using `supertest-fetch` (that is used in other tests)

The module is quite small, so a little things have to be tested:

- [ ] It doesn't identify browser UserAgent as a bot
- [ ] It identifies Google crawler as a bot
- [ ] it identifies node request as a bot

**Comment by aneeshrelan** [comment]
@talentlessguy Can you please assign this to me? Thanks!

**Comment by talentlessguy** [comment]
@aneeshrelan done

**Comment by aneeshrelan** [comment]
@talentlessguy For the 3rd task, "it doesn't identify node request as a bot", I'm not quite sure if I get this correctly, do we mean the request generated by the `supertest-fetch`? If yes, the user-agent comes out to be `node-fetch/1.0 (+https://github.com/bitinn/node-fetch)` which is being termed as a bot by the middleware

**Comment by talentlessguy** [comment]
@aneeshrelan my bad, it should identify as a bot

**Comment by aneeshrelan** [comment]
No worries. Have put up #112 to add tests

**Comment by talentlessguy** [comment]
Closed via #112
