### ISSUE TITLE
Implement `res.append`

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#117]
## Details

Should be put in a separate file (`append.ts`) in the `@tinyhttp/res` package and then re-exported in index.

## Link

Express implementation - https://github.com/expressjs/express/blob/master/lib/response.js#L721

Express docs - https://expressjs.com/en/5x/api.html#res.append

**Comment by Rashmi-K-A** [comment]
Hey, I would like to take this up!

**Comment by talentlessguy** [comment]
@Rashmi-K-A alright, assigning to you
