### ISSUE TITLE
Typescript +body-parser gives nextfunction error?

### ISSUE THREAD

**Issue by creepinson** [talentlessguy/tinyhttp#12]
**Describe the bug**
In the readme you said tinyhttp has "Full Express middleware support", but body-parser doesn't seem to work here as seen in the examples/auth folder in this repository. 

```
Argument of type 'NextHandleFunction' is not assignable to parameter of type 'string | AsyncHandler | SyncHandler'.
  Type 'NextHandleFunction' is not assignable to type 'AsyncHandler'.
    Types of parameters 'next' and 'next' are incompatible.
      Type 'NextFunction | undefined' is not assignable to type 'NextFunction'.
        Type 'undefined' is not assignable to type 'NextFunction'.
```

**To Reproduce**

Use **typescript** and body-parser and tinyhtttp and use the following line:
```
app.use(bodyParser.urlencoded({ extended: false }));
```

**Expected behavior**
I expected it to not give an error about the NextFunction.

**Versions**

* `node`: 12
* `@tinyhttp`: 0.2.3

![Error image](https://f.uwu.cam/files/233105.png)

**Comment by creepinson** [comment]
I also had this issue with my own middleware, seems like it wants the next function parameter of the middleware to be optional.  Doing `next?: NextFunction` instead of `next: NextFunction` seems to work, but not for other third-party middleware.

**Comment by talentlessguy** [comment]
Hi, thanks for the report. In README it meant not TypeScript support but *actual* support, still, I will need to fix it (the fix is very easy though, so PRs welcome)

I will fix the typings in the core soon to resolve the type conflict.

**Comment by talentlessguy** [comment]
@creepinson Should be fix now, with `0.2.4`:

````sh
pnpm i @tinyhttp/app@0.2.4
```

**Comment by creepinson** [comment]
It doesn't seem to work, it ives the same error about NextHandleFunction.  I think the body-parser function expects the next function to be defined, not optional.

I navigated to body-parser's dependency, connect, and in its type definitions the handler is like this:
`export type NextHandleFunction = (req: IncomingMessage, res: http.ServerResponse, next: NextFunction) => void;`
not this
` export type NextHandleFunction = (req: IncomingMessage, res: http.ServerResponse, next?: NextFunction | undefined) => void;`

**Comment by talentlessguy** [comment]
@creepinson

the [example](https://github.com/talentlessguy/tinyhttp/blob/master/examples/auth/index.js) with working `body-parser` that has types doesn't throw errors (at least the editor didn't say anything)

I can't make `NextFunction` required, because it will break things in a very wide amount of cases.

Could you please provide what typescript version do you use?

Also, a side question, did you install and build tinyhttp repo using `pnpm`? Because with `pnpm` the github repo examples work fine to me.

**Comment by creepinson** [comment]
Hmm... I am using pnpm, and I know that the example works fine, that's why I'm confused as well. I am using typescript 3.9.6, which I'm pretty sure is the latest.

**Comment by creepinson** [comment]
I don't know if this should go in a second issue but I'm also having trouble with  my custom async middleware...It seems to hang on loading the POST request and the logger middleware doesnt print anything related to that request. It also seems to block any app.use() lines after the line that is cuasing it to hang, which causes 404 to not work. I'm not sure what the problem is with my code (im using async/await with bcrypt and mongodb) but it shouldnt block other methods after it? What's weird is that app.get() lines that are BEFORE the problematic line work totally fine. I'll post my code here if needed but I'm not sure what is causing it to hang. I'm pretty sure ive handled all the errors AND changed some of the functions to async functions.

**Comment by talentlessguy** [comment]
@creepinson 

the example works fine without TS errors in the editor:

![image](https://user-images.githubusercontent.com/35937217/87701950-649e9d00-c7a1-11ea-888d-dc371bf42c44.png)

**Comment by creepinson** [comment]
Maybe its because you don't have a tsconfig or .ts file? I could be wrong about that though. Anyways setting strictFunctionTypes to false in tsconfig.json removes the error - so it works, but it might not be the best solution.

**Comment by talentlessguy** [comment]
@creepinson the example doesn't even use TS. It's JavaScript. Still, there's no error :thinking: 

altho I cannot reproduce it at all. maybe it's a VS Code issue, try updating it.
