### ISSUE TITLE
Write tests for etag

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#133]
there are some tests written for etag already, but there needs to be more of them:

- [ ] should reject number entities
- [ ] `Buffer`
  - [ ] should work for empty buffer
  - [ ] should generate a strong ETag
- [ ] `fs.Stats`
  - [ ] should generate a weak ETag
- [ ] `weak` option
  - [ ] should generate a strong eTag when is set to false
  - [ ] should generate a weak eTag when set to true

**Comment by MaurizioPz** [comment]
great

**Comment by talentlessguy** [comment]
Closed via #137
