### ISSUE TITLE
Write tests for @tinyhttp/req

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#140]
- [ ] `req.range`
  - [ ]  should return parsed ranges
  - [ ] should cap to the given size
  - [ ] should cap to the given size when open-ended
  - [ ] should have a .type
  - [ ] should accept any type
  - [ ] should return undefined if no range
  - [ ] with `options`
    - [ ] Should return combined ranges if `combine` set to true
- [ ] `req.is`
  - [ ] should return the given MIME type when matching
  - [ ] should return false when not matching
  - [ ] should return false when `Content-Type` header is not present
  - [ ] Should lookup the MIME type with the extension given (e.g. `req.is('json')`
  - [ ] Should ignore charset
  - [ ] more coming soon...
- [ ] more coming soon...

**Comment by MaurizioPz** [comment]
Thanks

**Comment by talentlessguy** [comment]
Closed via #142

**Comment by atif-saddique-deel** [comment]
this also should have been covered in tests here.
https://github.com/tinyhttp/tinyhttp/issues/407

`req.route` always returns `undefined`
https://tinyhttp.v1rtl.site/docs#reqroute

**Comment by talentlessguy** [comment]
> this also should have been covered in tests here.
> https://github.com/tinyhttp/tinyhttp/issues/407
> 
> `req.route` always returns `undefined`
> https://tinyhttp.v1rtl.site/docs#reqroute

you need to set `enableReqRoute` to true
