### ISSUE TITLE
Create markdown blog example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#141]
The blog should:

- automatically serve (and compile to html) markdown files
- extract front matter

Example structure:

```
server.js
pages/
   hello.md
   about.md
index.html
```

index.html must contain a list of all markdown pages using extracted front matter.

front matter should consist of the following properties:

- `slug` Slug of an article
- `date` timestamp
- `topic` page topic (can be anything)

Modules to be used (recommended, if you find better ones feel free to suggest):

- [gray-matter](https://github.com/jonschlinkert/gray-matter) for parsing front matter
- [@tinyhttp/markdown](https://github.com/talentlessguy/tinyhttp/tree/master/packages/markdown) for serving markdown

**Comment by HunterJS-bit** [comment]
I would like to give it a try, can I work on this ?

**Comment by talentlessguy** [comment]
@HunterJS-bit yup, assigning you

to get started, check the CONTRIBUTING.md file with all of the instructions of setting up an example

**Comment by talentlessguy** [comment]
@HunterJS-bit `@tinyhttp/markdown`'s functionality might be not enough to do gray matter parsing, then you could maybe try using `fs.readFile` (from `fs/promises`) and `marked` (or any other markdown parser)

**Comment by HunterJS-bit** [comment]
@talentlessguy  Greate thank you will check it out

**Comment by HunterJS-bit** [comment]
@talentlessguy  created pull request #152

**Comment by talentlessguy** [comment]
@HunterJS-bit I updated the issue description with more concise requirements for front matter parsing

**Comment by talentlessguy** [comment]
closed via abce6f38d9ede6c2431c736c427ff66a5c3f987a
