### ISSUE TITLE
Write tests for @tinyhttp/send

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#143]
- [ ] send
      - [ ] `send`
        - [ ] remove headers for 301 and 204 statuses ([codecov](https://codecov.io/gh/talentlessguy/tinyhttp/src/master/packages/send/src/send.ts#L45))
        - [ ] set `Content-Type` to `application/octet-stream` if the header hasn't been set before
      
      - [ ] `sendFile`
        - [ ] throw if path is not absolute ([codecov](https://codecov.io/gh/talentlessguy/tinyhttp/src/master/packages/send/src/sendFile.ts#L37))
        - [ ] `Content-Type` header (based on filename) is set properly
        - [ ] `options.headers` sets all required headers

**Comment by alcar** [comment]
Thanks, @talentlessguy! I'll start working on it soon!

**Comment by alcar** [comment]
Thanks, @talentlessguy! I'll start working on it soon!

**Comment by alcar** [comment]
@talentlessguy, I'm trying to make the 2nd `send` test pass, but I think the module may be missing a `res.end` for buffers. Adding it seems to solve the problem, but, since I'm new to the codebase, it'd be great if you could confirm that it makes sense :sweat_smile:

**Comment by talentlessguy** [comment]
@alcar how is it going?

**Comment by alcar** [comment]
@talentlessguy only managed to actually take a look at the code yesterday, and now I'm writing the final 2 tests, so should have a PR ready in a bit! Sorry for the delay!
