### ISSUE TITLE
Create PostgreSQL + TypeORM example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#145]
Create an example tinyhttp application that uses PostgreSQL for a database and TypeORM for an ORM

**Comment by Luiginator** [comment]
I would like to work on this one.

**Comment by talentlessguy** [comment]
@Luiginator I could adding you but... imo would be cooler if some beginner will make it instead

let's wait for 24 hours and if no one else wants to work on it, I'll assign it to you

**Comment by jkreller** [comment]
May I try that one?
What about implementing a ToDo-List API for example?

**Comment by jkreller** [comment]
I saw that the PostgreSQL example implements a user API. So probably that would be a better way to do it

**Comment by talentlessguy** [comment]
@jkreller better make smth more than a todo list, and yup, I can assign you

**Comment by jkreller** [comment]
Opened PR #151

**Comment by talentlessguy** [comment]
Closed via #151
