### ISSUE TITLE
Create search example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#146]
Create a server-side Google-like search, similar to [Express search example](https://github.com/expressjs/express/tree/master/examples/search)

example folder: `search`

Redis can be used, although it isn't a necessity

a simple array will also work

a bonus point would be making a cool layout for it (google clone but w/ tinyhttp logo idk) :D

**Comment by jkreller** [comment]
I would like to try that one! May I?

**Comment by talentlessguy** [comment]
@jkreller yup, assigning to you

feel free to ask questions if you have any

**Comment by jkreller** [comment]
@talentlessguy I got a problem running any example in the examples folder by following the README.md files. When starting the scripts it tells me that it cannot find the @tinyhttp/app package. Are there any additional steps necessary?

**Comment by talentlessguy** [comment]
> @talentlessguy I got a problem running any example in the examples folder by following the README.md files. When starting the scripts it tells me that it cannot find the @tinyhttp/app package. Are there any additional steps necessary?
> I have the newest version of pnpm, node and followed [CONTRIBUTING.md](https://github.com/talentlessguy/tinyhttp/blob/master/CONTRIBUTING.md)

what script did you start?

**Comment by talentlessguy** [comment]
ah, to run any of the examples, you need to run `pnpm i @tinyhttp/app` in the example folder

that's because it needs to link before using it

**Comment by jkreller** [comment]
Probably the contribution- or better the example-Readme should be adjusted. What do you think about?

**Comment by talentlessguy** [comment]
@jkreller what do you mean? that `@tinyhttp/app` should be installed to the example in order to run it?

I can put it in CONTRIBUTING.md file, but usually these examples are meant to check online on github.

also, do you still struggle to set up an example? or it's working fine now?

**Comment by jkreller** [comment]
@talentlessguy I just found it confusing as someone who wants to run the example from the repository. But you are right, if the purpose is to check it online it's not necessary.

**Comment by jkreller** [comment]
It worked fine now. Resolved with #148, I hope ;)

**Comment by talentlessguy** [comment]
@jkreller the PR needs some small fixes, pls check my comments

**Comment by jkreller** [comment]
@talentlessguy Added another commit. Also had the muse to adjust the layout to be Google-like 😄

**Comment by talentlessguy** [comment]
Closed via #148
