### ISSUE TITLE
reqIs does not correctly parse the Content-Type header

### ISSUE THREAD

**Issue by BRA1L0R** [talentlessguy/tinyhttp#150]
Thanks @MaurizioPz for finding this bug

**Describe the bug**
`reqIs` does not separate the content type from the charset
This is actually an issue in another package called `@tinyhttp/type-is`
```ts
function tryNormalizeType(value: string) {
  if (!value) return null

  try {
    return normalizeType(value)
  } catch (err) {
    return null
  }
}
```

as you can see here (line 12, @tinyhttp/type-is/index.ts) the function for type normalization is empty and does not remove the charset part from the content-type header

**To Reproduce**
( related issue #142 )
Running this test results in an error, since type-is does not properly separate the actual content from the charset info.
```ts
it('should ignore charset', async () => {
    const app = runServer((req, res) => {
      expect(reqIs(req)('text/html')).toBe('text/html')
      res.end()
    })
    await makeFetch(app)('/', {
      headers: {
        'Content-Type': 'text/html; charset=UTF-8',
      },
    })
    expect.assertions(1)
  })
```

**Expected behavior**
type-is.typeIs should separate the `text/html` part of the Content-Type header from `; charset=UTF-8`

**Versions**
* `node`: 14.13.0
* `@tinyhttp/app`: 0.4.3

**Comment by talentlessguy** [comment]
Anyone can submit a bugfix :D
