### ISSUE TITLE
Create Caddy example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#158]
Create an example of using tinyhttp and a web server, [Caddy](https://caddyserver.com/) in this case.

The demo should show that `Host`, `X-Forwarded-For` and are passed to `req.ip` and `req.host` respectively.

The demo also must have HTTPS enabled (self signed would be fine) to show that `req.secure` also works.

File structure of the demo:

```
caddy
  Caddyfile
  package.json
  README.md
  server.js
```

**Comment by huseyinsimsekk** [comment]
I looked at this issue. I don't know Candy  :) but I can do it. Please assign it to me. I think I can do that like Http2 example

**Comment by talentlessguy** [comment]
@huseyinsimsekk HTTP/2 example is already present in the examples folder

and if you don't know Caddy I can't assign you, because you won't be able to create an example with a technology you don't know

**Comment by huseyinsimsekk** [comment]
Ok. I see

**Comment by talentlessguy** [comment]
Closed via #164
