### ISSUE TITLE
Create Angular SSR example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#159]
Docs: https://angular.io/guide/universal

**Comment by pedchenkoroman** [comment]
Hey, could you assign to me? I'd like to try to create this one.

**Comment by talentlessguy** [comment]
@pedchenkoroman done

**Comment by talentlessguy** [comment]
@pedchenkoroman how is it going? :) are there any problems you faced? (just checking if you didn't give up lol)

**Comment by pedchenkoroman** [comment]
I'm still on it. It is not easy as I thought. If you have someone who can do it better or faster please feel free assign to it. It's my first experience to contribute to open source.

**Comment by talentlessguy** [comment]
I didn't realize the complexity and bloat of Angular apps so closing the issue.
