### ISSUE TITLE
Implement `app.param`

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#162]
Express docs: https://expressjs.com/en/4x/api.html#app.param

Express implementation: https://github.com/expressjs/express/blob/master/lib/application.js#L321

Note that tinyhttp uses `regexparam` to parse query params from a URL. Most probably you'll use it while implementing this method

- [ ] Implement the method
- [ ] JSDoc comments
- [ ] Tests (`__tests__/core/app.test.ts`)
- [ ] Docs (on the website, `site/pages/md/docs.md`)

**Comment by ajkachnic** [comment]
Hello! I just found this project (and I think it’s really cool), but do you mind if I take a swing at this? How difficult do you think it would be to do?

**Comment by talentlessguy** [comment]
Hello @ajkachnic! This issue is labeled as `medium` because it requires some more than usual effort to do. It doesn't mean that it's impossible to implement the `param` method, it just means that you'll have to do some research and try different things before you get the final result.

So, returning back to `app.param` implementation, it will probably slightly differ from Express implementation. Although, it should match the original method as close as possible.

So, it should work like this:

```ts
app.param('param_name', (req, res, next, paramValue) => {
  console.log(`param value - ${paramValue}`)
  next()
})
```

**Comment by ajkachnic** [comment]
Yeah I'd like to work on it!

**Comment by talentlessguy** [comment]
@ajkachnic assigning you then!

**Comment by talentlessguy** [comment]
@ajkachnic updated the issue description with a todo

**Comment by talentlessguy** [comment]
Also, a note. `@tinyhttp/url` contains the special function to get request params, so you don't have to make regexparam a direct dependency. Just use the `getURLParams` function

**Comment by ajkachnic** [comment]
This is probably a stupid question, but this should be included in the `App` class right? I'm somewhat sure, but it could also be in `Router` so I wanted to confirm

Or, would this be similar to the way express has it were the App calls the internal router method?

**Comment by talentlessguy** [comment]
@ajkachnic it should be a method of the `App` class

**Comment by talentlessguy** [comment]
how is it going, @ajkachnic? do you face some difficulties that you need help with?

(sorry if i'm annoying just checking if things are going alright)

**Comment by talentlessguy** [comment]
Only now I noticed that `app.param` is deprecated

> The following section describes app.param(callback), which is deprecated as of v4.11.0.

closing because tinyhttp is not going to implement deprecated methods
