### ISSUE TITLE
Test `@tinyhttp/session`

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#163]
tests are almost identical to Express `session` module, so there are references to source of their tests.

- [ ] `SessionManager(opts)`
  - [ ] more coming soon....
- [ ] `getSession(req, res)`
  - [x] `session.save(cb)`
    - [x] Should save session to store ([src](https://github.com/expressjs/session/blob/master/test/session.js#L1762))
    - [x] Should prevent end-of-request save ([src](https://github.com/expressjs/session/blob/master/test/session.js#L1780))
    - [x] Should prevent end-of-request save on reloaded session
  - [x] `session.touch(cb)` ([src](https://github.com/expressjs/session/blob/master/test/session.js#L1829))
  - [ ] `session.cookie` ([src](https://github.com/expressjs/session/blob/master/test/session.js#L1864))
  - [x] `session.originalMaxAge` ([src](https://github.com/expressjs/session/blob/master/test/session.js#L1948))
  - and the rest of `session` properties :D
- [ ] `Cookie`
    - [ ] `new Cookie(opts)`
      - [x] `expires` is falsy be default
      - [x] `httpOnly` is true by default

this list is in progress, so pls ping once finished writing those tests

**Comment by alcar** [comment]
Thanks, @talentlessguy! Could you please assign it to me?

**Comment by alcar** [comment]
Hey, @talentlessguy! I'm not sure if I'm correctly adapting Express' end-of-request tests — could you please give me some tips on how to test that using this library?

**Comment by talentlessguy** [comment]
@alcar I think the test should look smth like this:

```ts
// ...
function shouldSetSessionInStore(store) {
  let _set = store.set
  let count = 0

  store.set = function set () {
    count++
    return _set.apply(this, arguments)
  }

  return count === 1
}

const store = new MemoryStore()
    const getSession = SessionManager({
      store,
      secret: 'test',
    })

const { fetch } = InitAppAndTest(async (req, res) => {
    const session = await getSession(req, res)
    session.hit = true
    session.save(err => err ? res.end(err.message) : res.end('saved')
})

const res = await fetch('/').then(() => expect(shouldSetSessionInStore(store).toBe(true))

const text = await res.text()

expect(res.status).toBe(200)

expect(text).toBe('saved')
```

**Comment by alcar** [comment]
Yeah, I was doing something similar, but `set` doesn't seem to be called, so `count` never goes up and, consequently, the test fails. Do you think there may be something missing in the implementation?

**Comment by talentlessguy** [comment]
@alcar more like the `shouldSetSessionInStore` function works not as expected. `set` is called (I think?) but not inside of `shouldSetSessionInStore`

prob worth rewriting that helper function

**Comment by alcar** [comment]
Hmm, I see! Okay, I'll give that a try.

Just for reference, here is what I currently have:
```ts
it('should prevent end-of-request save', async () => {
  const store = new MemoryStore()

  const getSession = SessionManager({
    store,
    secret: 'test',
  })

  const { fetch } = InitAppAndTest(async (req, res) => {
    const session = await getSession(req, res)

    session.save((err) => {
      if (err) {
        return res.end(err.message)
      }

      res.end('saved')
    })
  })

  await fetch('/').expectStatus(200).expectBody('saved')

  shouldSetSessionInStore(store)
})

function shouldSetSessionInStore(store: MemoryStore) {
  const _set = store.set

  let count = 0

  store.set = function set() {
    count++

    return _set.apply(this, arguments)
  }

  assert.ok(count === 1, 'should set session in store')
}
```

I was also wondering why they do two consecutive requests and set a cookie [in their tests](https://github.com/expressjs/session/blob/master/test/session.js#L1790) :thinking:

**Comment by alcar** [comment]
The tests below pass, but they're basically only checking if `.set` was called once. I'm not sure if I understand what kind of behavior we're trying to test.

```ts
it('should prevent end-of-request save', async () => {
  const store = new MemoryStore()

  const _set = store.set

  let setCount = 0

  store.set = function set() {
    setCount++

    return _set.apply(this, arguments)
  }

  const getSession = SessionManager({
    store,
    secret: 'test',
  })

  const { fetch } = InitAppAndTest(async (req, res) => {
    const session = await getSession(req, res)

    session.save((err) => {
      if (err) {
        return res.end(err.message)
      }

      res.end('saved')
    })
  })

  await fetch('/').expectStatus(200).expectBody('saved')

  expect(setCount).toBe(1)
})

it('should prevent end-of-request save on reloaded session', async () => {
  const store = new MemoryStore()

  const _set = store.set

  let setCount = 0

  store.set = function set() {
    setCount++

    return _set.apply(this, arguments)
  }

  const getSession = SessionManager({
    store,
    secret: 'test',
  })

  const { fetch } = InitAppAndTest(async (req, res) => {
    const session = await getSession(req, res)

    session.reload(() => {
      session.save((err) => {
        if (err) {
          return res.end(err.message)
        }

        res.end('saved')
      })
    })
  })

  await fetch('/').expectStatus(200).expectBody('saved')

  expect(setCount).toBe(1)
})
```

**Comment by talentlessguy** [comment]
@alcar we're trying to test whether the session is saved at the end of HTTP response

regarding `session.save`:

> This method is automatically called at the end of the HTTP response if the session data has been altered (though this behavior can be altered with various options in the middleware constructor). Because of this, typically this method does not need to be called.

**Comment by alcar** [comment]
Hmm, so, if I understood correctly, the tests above are enough because they confirm that `.set` is being called once, which means that it's only called by us, and not automatically in the end of the request?

**Comment by talentlessguy** [comment]
@alcar I think yes?

**Comment by alcar** [comment]
@talentlessguy, I've just opened a PR (#173) with some tests! I don't think I'll have time to work on the remaining ones for now, so perhaps we should let someone else pick them up :confused:

**Comment by talentlessguy** [comment]
@alcar alright, will check for ur tests then but won't close this issue

**Comment by talentlessguy** [comment]
I took the decision to delete `@tinyhttp/session`

the current implementation is buggy as hell and is too huge to maintain with all other modules

better use `next-session`. it works with tinyhttp pretty well: https://github.com/hoangvvo/next-session
