### ISSUE TITLE
Implement `res.sendFile`

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#17]
**Is your feature request related to a problem? Please describe.**

`res.sendFile` is commonly used in Express apps. tinyhttp must have one too.

**Describe the solution you'd like**

Implement `res.sendFile` based on existing `res.send` function

**Additional context**

Express docs reference: http://expressjs.com/en/5x/api.html#res.sendFile
Express implementation:  https://github.com/expressjs/express/blob/ecd8a08c1c9c4d60b466b451fd1f5c3fe8a5fb23/lib/response.js#L403

**Comment by ahmad-reza619** [comment]
Hi @talentlessguy i would like to take this on, is the shape of sendFile function has to be just like express?

**Comment by talentlessguy** [comment]
@ahmad-reza619 yeah must work the same

code might differ

**Comment by talentlessguy** [comment]
@ahmad-reza619 also, if possible, it shouldn't introduce any new dependencies

**Comment by ahmad-reza619** [comment]
is this sendFile function will be able to send any kind of file? like maybe mp3 file?

**Comment by ahmad-reza619** [comment]
From what i see from express test case, it looked like it only send file with text inside it

**Comment by talentlessguy** [comment]
@ahmad-reza619 hmmm I think u're right but I by myself can't undertsand whether it sends a file with Content-Disposition header to download it, or just raw file

need to investiage more and re-check the implementation

**Comment by talentlessguy** [comment]
implemented in 2bba94ce9ee521a3bc10d448757c73889f6f8e1c, but not 1:1 to express

need more time to make it have the same API

**Comment by talentlessguy** [comment]
I think it's implemented properly, if anyone has suggestions, feel free to write here and I will re-open the thread
