### ISSUE TITLE
Error when requesting route with params and query

### ISSUE THREAD

**Issue by fabianmoronzirfas** [talentlessguy/tinyhttp#175]
**Describe the bug**

The server hangs itself when I try to send a GET request to a route where I use `req.params` and `req.query` e.g.`/cats/:catId/moods?food=fish`

**To Reproduce**

I prepared a small repo to reproduce that error.

```bash
git clone https://github.com/fabianmoronzirfas/tinyhttp-request-error.git
npm ci
npm run dev
```

In another session

```bash
curl --request GET \
  --url 'http://localhost:3000/cats/1/moods?food=fish' 
```

**Expected behavior**

I expect the console to log
```js
  console.log(req.query);
  console.log(req.params);
```
and to return a response.

```js
  res.json({ message: "add a query string", url: req.url });
```

**Versions**

* `node`: v14.13.1
* `@tinyhttp/app`: 0.5.6

**Comment by talentlessguy** [comment]
Interesting... i don't know yet what's going on here. Feels like it hangs because some kind of handler is stuck and doesn't pass the index to the next ware...

**Comment by talentlessguy** [comment]
Spotted the bug, it hangs in here:

https://github.com/talentlessguy/tinyhttp/blob/master/packages/app/src/app.ts#L215

gonna fix asap

thx for reporting!

**Comment by talentlessguy** [comment]
Looks like i'm misusing the `regexparam` package...

**Comment by talentlessguy** [comment]
Aaaaaaaaaaaand I fixed it!

Try now with:

```
pnpm i @tinyhttp/app@0.5.8
```

**Comment by talentlessguy** [comment]
@all-contributors add @fabianmoronzirfas for bug

**Comment by fabianmoronzirfas** [comment]
> Aaaaaaaaaaaand I fixed it!
> 
> Try now with:
> 
> ```
> pnpm i @tinyhttp/app@0.5.8
> ```

Works like a charm. Thank you
