### ISSUE TITLE
build error with tsc

### ISSUE THREAD

**Issue by fabianmoronzirfas** [talentlessguy/tinyhttp#176]
**Describe the bug**

While playing with @tinyhttp I ran into the following problem.
When trying to build with the `tsconfig.json` below, 

```json
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "lib": ["esnext"],
    "esModuleInterop": true
  }
}
```

I run into the following build error.  

```plain
> npm run build

> tinyhttp-request-error@0.0.1 build /Users/mememe/tmp/tinyhttp-build-error
> tsc

node_modules/@tinyhttp/app/dist/request.d.ts:4:24 - error TS7016: Could not find a declaration file for module 'range-parser'. '/Users/mememe/tmp/tinyhttp-build-error/node_modules/range-parser/index.js' implicitly has an 'any' type.
  Try `npm install @types/range-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'range-parser';`

4 import { Ranges } from 'range-parser';
                         ~~~~~~~~~~~~~~

node_modules/@tinyhttp/req/dist/index.d.ts:2:37 - error TS7016: Could not find a declaration file for module 'range-parser'. '/Users/mememe/tmp/tinyhttp-build-error/node_modules/range-parser/index.js' implicitly has an 'any' type.
  Try `npm install @types/range-parser` if it exists or add a new declaration (.d.ts) file containing `declare module 'range-parser';`

2 import parseRange, { Options } from 'range-parser';
                                      ~~~~~~~~~~~~~~


Found 2 errors.
```

What is a recommended typescript configuration? Or why do I get this error?
The `tsconfig.json` is taken from a https://prisma.io tutorial.

FYI:

- When I use the default `tsconfig.json` generated with `npx tsc --init` the build works fine.
- Also when I install the missing types the build works fine.

**To Reproduce**

I created a small [repo](https://github.com/fabianmoronzirfas/tinyhttp-build-error) to reproduce this.

```
git clone https://github.com/fabianmoronzirfas/tinyhttp-build-error.git
cd tinyhttp-build-error
npm ci
npm run build
```

**Expected behavior**

The build to pass.

**Versions**

* `node`: v14.13.1
* `@tinyhttp/app`: 0.5.6

**Additional context**

**Comment by talentlessguy** [comment]
Try adding

```json
"moduleResolution": "Node"
```

to your tsconfig

**Comment by fabianmoronzirfas** [comment]
Thanks for the swift reply. I added a build action here on GitHub and followed your suggestion. Unfortunately the build still fails. 

https://github.com/fabianmoronzirfas/tinyhttp-build-error/runs/1316673866?check_suite_focus=true

**Comment by talentlessguy** [comment]
@fabianmoronzirfas try this config:

```
{
  "compilerOptions": {
    "target": "es2019",
    "module": "ESNext",
    "esModuleInterop": true,
    "moduleResolution": "Node"
  }
}
```

it should work

**Comment by talentlessguy** [comment]
Looks like `"strict": true` is the root cause of why it fails to build

no clue what's happening, need to google

**Comment by talentlessguy** [comment]
Temporary solution: not using `"strict": true`

**Comment by fabianmoronzirfas** [comment]
> Temporary solution: not using `"strict": true`

Yes. Thank you. That works 👍
