### ISSUE TITLE
Create OpenAPI validator example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#186]
Create an example using [express-openapi-validator](https://github.com/cdimascio/express-openapi-validator) and tinyhttp

**Comment by MVEMCJSUNPE** [comment]
Can I work on this issue?

**Comment by talentlessguy** [comment]
@MVEMCJSUNPE yup

**Comment by MVEMCJSUNPE** [comment]
Thanks. Btw, maybe I'm just stupid, but I can't seem to run the examples? My node version is v15.2.0, pnpm version is 5.11.1, and I'm pretty sure I've followed the instructions in CONTRIBUTING.md (pnpm i, pnpm i -r, pnpm build). When I try running an example (say vue-ssr), I get 
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@tinyhttp/app' imported from C:\Users\Username\source\repos\tinyhttp\examples\vue-ssr\index.js
```

I'm running Windows, so maybe that could be a problem.

**Comment by talentlessguy** [comment]
@MVEMCJSUNPE run `pnpm i @tinyhttp/app` inside of the example so it links the package

**Comment by MVEMCJSUNPE** [comment]
Maybe I'm just being dumb again, but I don't think that express-openapi-validator works with tinyhttp. After changing the require statements to import statements in express-openapi-validator's first [example](https://github.com/cdimascio/express-openapi-validator/blob/master/examples/1-standard/app.js) and replacing express() with new App, app.js looks something like this: 
```js
import { App } from '@tinyhttp/app'
// import express from 'express'
import Pets from './services/index.js'

import bodyParser from 'body-parser'
import OpenApiValidator from 'express-openapi-validator'

import path from 'path'
import { fileURLToPath } from 'url'
import http from 'http'

const port = 3000;
const app = new App();

// For some reason, __dirname doesn't work in ES module style js
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const apiSpec = path.join(__dirname, 'api.yaml');

// 1. Install bodyParsers for the request types your API will support
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.text());
app.use(bodyParser.json());

// Optionally serve the API spec
// app.use('/spec', express.static(apiSpec));

//  2. Install the OpenApiValidator on your express app
app.use(
  OpenApiValidator.middleware({
    apiSpec,
    validateResponses: true, // default false
  }),
);
const pets = new Pets();
// 3. Add routes
app.get('/v1/ping', function (req, res, next) {
  res.send('pong');
});
app.get('/v1/pets', function (req, res, next) {
  res.json(pets.findAll(req.query));
});

app.post('/v1/pets', function (req, res, next) {
  res.json(pets.create({ ...req.body }));
});

app.delete('/v1/pets/:id', function (req, res, next) {
  res.json(pets.delete(req.params.id));
});

app.get('/v1/pets/:id', function (req, res, next) {
  const pet = pets.findById(req.params.id);
  return pet
    ? res.json({ pet })
    : res.status(404).json({ message: 'not found' });
});

// 3a. Add a route upload file(s)
app.post('/v1/pets/:id/photos', function (req, res, next) {
  // DO something with the file
  // files are found in req.files
  // non file multipar params are in req.body['my-param']
  console.log(req.files);

  res.json({
    files_metadata: req.files.map((f) => ({
      originalname: f.originalname,
      encoding: f.encoding,
      mimetype: f.mimetype,
      // Buffer of file conents
      // buffer: f.buffer,
    })),
  });
});

// 4. Create a custom error handler
app.use((err, req, res, next) => {
  // format errors
  res.status(err.status || 500).json({
    message: err.message,
    errors: err.errors,
  });
});

app.listen(port, () => {
  console.log(`Listening on port ${port}`);
})
```
However, I get `Cannot read property param of 'undefined'`: 
<img width="731" alt="openapi_error" src="https://user-images.githubusercontent.com/10354503/99161466-582b4200-26b8-11eb-9937-2f66e0ed7e13.png">

With express, express-openapi-validator works, however: 
<img width="710" alt="openapi_works" src="https://user-images.githubusercontent.com/10354503/99161492-b3f5cb00-26b8-11eb-9ec9-426411c07e1b.png">

I suspect that it would have to do with the differences in how the use method is implemented in express and tinyhttp, and I would try to fix the error myself; however, I seem to have a hard time finding any instance of the use method in packages/app/src/app.ts.

**Comment by talentlessguy** [comment]
@MVEMCJSUNPE 

`.use(...)` method is located in `@tinyhttp/router`'s `Router` class

**Comment by MVEMCJSUNPE** [comment]
So digging through the source code and doing some debugging, I've finally found the reason why express-openapi-validator isn't working with tinyhttp. As we can see from this stack trace, the error is occurring somewhere in openapi.validator.js, which is the compiled version of openapi.validator.ts. 
<img width="958" alt="express_param_failure" src="https://user-images.githubusercontent.com/10354503/99346317-f6a2d900-2859-11eb-9bef-b74f248b63ae.png">
If we look at openapi.validator.js, we see that the param method is being called as part of app:
<img width="578" alt="openapi_validator_param" src="https://user-images.githubusercontent.com/10354503/99346587-8fd1ef80-285a-11eb-8db0-6acf5bad17f2.png">
I know from this [issue](https://github.com/talentlessguy/tinyhttp/issues/162#issue-722398572) that someone is currently working on param at the moment, but I don't see a way to get express-openapi-validator and tinyhttp to work together until param gets implemented.

**Comment by talentlessguy** [comment]
@MVEMCJSUNPE thanks for taking time to find the root cause! Sorry that I didn't look it up before suggesting to use it :(

and yeah `app.param` isn't implemented

so now we have two options:

- we find an alternative of this package
- we close the issue

gonna search some other modules up and send here

**Comment by talentlessguy** [comment]
could you please try these instead?

- https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-response-validator
- https://github.com/Hilzu/express-openapi-validate
