### ISSUE TITLE
Router error - TypeScript errors

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [talentlessguy/tinyhttp#192]
**Describe the bug**

When linking the router to my app and going to the path, the process crashes and returns an error

**To Reproduce**

1. Create an App (TypeScript)
2. Create a router (TypeScript)
3. Use the router in the app
4. Go to the API route

**Expected behavior**

The app should not crash and should return the requested response

**Versions**

* `node`: 15
* `@tinyhttp/app`: 1.0.1
* TypeScript: 4.1.2

**Additional context**

Error that crashes the process: 

```
F:\Projects\Visual Studio Code Projects\notes.app\server\node_modules\@tinyhttp\app\dist\index.cjs:269
            this.apps[subappPath].handler(req$1, res);
                                  ^
TypeError: this.apps[subappPath].handler is not a function
    at App.handler (F:\Projects\Visual Studio Code Projects\notey.app\server\node_modules\@tinyhttp\app\dist\index.cjs:269:35)
    at Server.<anonymous> (F:\Projects\Visual Studio Code Projects\notey.app\server\node_modules\@tinyhttp\app\dist\index.cjs:324:49)
    at Server.emit (node:events:329:20)
    at Server.EventEmitter.emit (node:domain:467:12)
    at parserOnIncoming (node:_http_server:919:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:126:17)
```

There are also a few errors TypeScript is giving me (commented in the code)
Code I have: 

<details>
   <summary>App file</summary>

   ```ts
import { App } from "@tinyhttp/app";
const app = new App();
const port = Number(process.env.PORT) || 3030;
import api from "./routes/api";

/* 
   other middleware..
*/

/*
	Error:
	Argument of type 'Router<any, IncomingMessage, ServerResponse>' is not assignable to parameter of type 'App<any, Request, Response> | AsyncHandler<Request, Response> | SyncHandler<Request, Response> | Handler<...>[] | undefined'.
  Type 'Router<any, IncomingMessage, ServerResponse>' is missing the following properties from type 'App<any, Request, Response>': locals, noMatchHandler, onError, settings, and 9 more.ts(2345)
*/
app.use("/api/v3", api);

app.listen(port, () => Logger.listening(port));
   ```

</details>

<details>
   <summary>router file</summary>

   ```ts
import { Router } from "@tinyhttp/router";

const api = new Router();

api.get("/", (req, res) => {
  /*
	Error: 
    Property 'json' does not exist on type 'ServerResponse'.
  */
  return res.json({
    msg: "Welcome to notey.app's API",
    status: "success",
  });
});

export default api;

   ```

</details>

This is my first time using your package so, I might be doing something completely wrong?

**Comment by talentlessguy** [comment]
`Router` shouldn't be used in HTTP apps, it's a general abstraction for routing, without any request and response extensions. It doesn't even have a `handle` function.

Instead, you should use `App`. It has all required properties and you can connect apps to other apps, as described in [the guide](https://tinyhttp.v1rtl.site/learn#subapps)

**Comment by Dev-CasperTheGhost** [comment]
Ahh, thanks!
