### ISSUE TITLE
routing syntax

### ISSUE THREAD

**Issue by simone-sanfratello** [talentlessguy/tinyhttp#196]
Hello everyone,

I can't find in the documentation the syntax supported on routes. I suppose express syntax is supported, but it is not: for example, I tried using regexp in routes.

Is it possible to update the documentation?

I would be happy to do that, if anyone could give me an overview on what is supported and what is not

Thanks

**Comment by talentlessguy** [comment]
Regex aren't supported as paths but you can add it via PR

also, I'm not sure what functionality you're missing, could you please be more concise?

as for paths, strings are supported, e.g. `/:hello`

for wares, handler functions, list of wares and array of wares are supported, it's mentioned [here](https://tinyhttp.v1rtl.site/learn#routing)

**Comment by simone-sanfratello** [comment]
Thanks for the quick response! That's what I was looking for.
