### ISSUE TITLE
original app settings aren't inherited for subapps

### ISSUE THREAD

**Issue by creepinson** [talentlessguy/tinyhttp#199]
**Is your feature request related to a problem? Please describe.**
I have setup a subapp with `new App()` and used it for a login page. I have also set up a few middlewares and the pug view engine in the parent app instance. However, it keeps logging:
> (node:23948) UnhandledPromiseRejectionWarning: TypeError: this.engines[options.ext] is not a function

**Describe the solution you'd like**
res.render in the sub app should render the page. 

**Describe alternatives you've considered**
I have tried setting the same engine property in the subapp and it works fine, which is annoying because I don't want to copy the settings to each subapp.

**Additional context**
Maybe you could add a { inherit: booelan } property to the app options upon constructing a new app instance? That way people can choose not to inherit those properties. By the way, this also applies to app.set("views", ...) and not just the view engine.

**Comment by creepinson** [comment]
Also, this could go in a different issue but since this is related to the subapp issue:

I keep getting 404's on the subapp root page ("/admin/") but on "/admin/login" it works and actually tries to render the page.

Example:
```typescript
export const adminApiRouter = new App({});
adminApiRouter.engine("pug", (path, data, opts, cb) =>
    renderFile(path, { opts, ...data }, cb)
);
adminApiRouter.set("views", path.join(__dirname, "../views"));
adminApiRouter.post("/api/login", async (req, res) => {
    const session = await getSession(req, res);
    const existingPass = config.toObject().adminPassword;
    if (req.body.password === existingPass) {
        session.auth = true;
        return res.status(200).redirect("/admin");
    } else {
        session.auth = false;
        return res.redirect("/admin/login");
    }
});
adminApiRouter.get("/login", (req, res) => res.render("admin/auth/login.pug"));
adminApiRouter.get("/", async (req, res) => {
    const session = await getSession(req, res);
    if (session.auth && session.auth === true)
        return res.status(403).render("content.pug", {
            header: "403 Forbidden",
            content: "You are not logged in.",
        });
    else
        return res.render("content.pug", {
            header: "Welcome",
            content: "Welcome, homelab administrator.",
        });
});
```

**Comment by talentlessguy** [comment]
> **Is your feature request related to a problem? Please describe.**
> I have setup a subapp with `new App()` and used it for a login page. I have also set up a few middlewares and the pug view engine in the parent app instance. However, it keeps logging:
> 
> > (node:23948) UnhandledPromiseRejectionWarning: TypeError: this.engines[options.ext] is not a function
> 
> **Describe the solution you'd like**
> res.render in the sub app should render the page.
> 
> **Describe alternatives you've considered**
> I have tried setting the same engine property in the subapp and it works fine, which is annoying because I don't want to copy the settings to each subapp.
> 
> **Additional context**
> Maybe you could add a { inherit: booelan } property to the app options upon constructing a new app instance? That way people can choose not to inherit those properties. By the way, this also applies to app.set("views", ...) and not just the view engine.

looks like it's tinyhttp bug because Express apps always inherits settings

will look into it

**Comment by talentlessguy** [comment]
> Also, this could go in a different issue but since this is related to the subapp issue:
> 
> I keep getting 404's on the subapp root page ("/admin/") but on "/admin/login" it works and actually tries to render the page.
> 
> Example:
> 
> ```ts
> export const adminApiRouter = new App({});
> adminApiRouter.engine("pug", (path, data, opts, cb) =>
>     renderFile(path, { opts, ...data }, cb)
> );
> adminApiRouter.set("views", path.join(__dirname, "../views"));
> adminApiRouter.post("/api/login", async (req, res) => {
>     const session = await getSession(req, res);
>     const existingPass = config.toObject().adminPassword;
>     if (req.body.password === existingPass) {
>         session.auth = true;
>         return res.status(200).redirect("/admin");
>     } else {
>         session.auth = false;
>         return res.redirect("/admin/login");
>     }
> });
> adminApiRouter.get("/login", (req, res) => res.render("admin/auth/login.pug")); // actually works (but has the issues with the app engine as mentioned above)
> adminApiRouter.get("/", async (req, res) => { // renders not found page for some reason...
>     const session = await getSession(req, res);
>     if (session.auth && session.auth === true)
>         return res.status(403).render("content.pug", {
>             header: "403 Forbidden",
>             content: "You are not logged in.",
>         });
>     else
>         return res.render("content.pug", {
>             header: "Welcome",
>             content: "Welcome, homelab administrator.",
>         });
> });
> 
> // main index.ts
> app.use("/admin", adminApiRouter);
> ```

please put it in the separate issue because it's not related to the original issue

**Comment by talentlessguy** [comment]
@creepinson I'm trying to reproduce the same thing with express and I get this:

```js
import { renderFile } from 'eta'
import express from 'express'

const app = express()

app.engine('eta', renderFile)

app.settings['a'] = 'b'

const subapp = express()

app.use(subapp)

console.log(subapp.engines) // {}
console.log(subapp.settings['a']) // b
```

doesn't look like it inherits the engine, maybe i'm doing something wrong here?

ofc we could add support to it even if it's not Express, but I'm not sure if it can be considered as a bug or not

**Comment by creepinson** [comment]
Oh, I guess I havent worked with engines enough to know that it wasnt a thing. Yeah, it seems like an option to inherit those would be nice as I was trying to organize my routes into folders but that means I'd have to copy the view engine code to each route file which seemed unnecessary.

**Comment by talentlessguy** [comment]
@creepinson you can solve it using a simple function:

```ts
// engine.ts
import { renderFile } from 'eta'
import { App } from '@tinyhttp/app'
export const enginedApp = (app: App) => {
  app.engine('eta', renderFile)

  return app
}

// server.ts

const app = enginedApp()

const app2 = enginedApp()
```

**Comment by talentlessguy** [comment]
> Also, this could go in a different issue but since this is related to the subapp issue:
> 
> I keep getting 404's on the subapp root page ("/admin/") but on "/admin/login" it works and actually tries to render the page.
> 
> Example:
> 
> ```ts
> export const adminApiRouter = new App({});
> adminApiRouter.engine("pug", (path, data, opts, cb) =>
>     renderFile(path, { opts, ...data }, cb)
> );
> adminApiRouter.set("views", path.join(__dirname, "../views"));
> adminApiRouter.post("/api/login", async (req, res) => {
>     const session = await getSession(req, res);
>     const existingPass = config.toObject().adminPassword;
>     if (req.body.password === existingPass) {
>         session.auth = true;
>         return res.status(200).redirect("/admin");
>     } else {
>         session.auth = false;
>         return res.redirect("/admin/login");
>     }
> });
> adminApiRouter.get("/login", (req, res) => res.render("admin/auth/login.pug")); // actually works (but has the issues with the app engine as mentioned above)
> adminApiRouter.get("/", async (req, res) => { // renders not found page for some reason...
>     const session = await getSession(req, res);
>     if (session.auth && session.auth === true)
>         return res.status(403).render("content.pug", {
>             header: "403 Forbidden",
>             content: "You are not logged in.",
>         });
>     else
>         return res.render("content.pug", {
>             header: "Welcome",
>             content: "Welcome, homelab administrator.",
>         });
> });
> 
> // main index.ts
> app.use("/admin", adminApiRouter);
> ```

cannot reproduce this, it works fine for me:

```js
import { App } from '@tinyhttp/app'

const app = new App()

const subapp = new App()

subapp.get('/', (req, res) => res.send(subapp.mountpath)) // 'blog'

subapp.get('/admin', (req, res) => res.send('aa')) // 'aa'

app.use('/blog', subapp)

app.listen(3000)
```

```sh
$ curl localhost:3000/blog
/blog
$ curl localhost:3000/blog
