### ISSUE TITLE
session: cannot find module 'express-session'

### ISSUE THREAD

**Issue by creepinson** [talentlessguy/tinyhttp#201]
**Describe the bug**

I can;t figure out what the problem is exactly but it keeps saying
```   │ 
  │ node_modules/.pnpm/@tinyhttp/session@1.0.7/node_modules/@tinyhttp/session/dist/index.d.ts:2:39 - error TS2307: Cannot find module 'express-session' or its corresponding type declarations.
  │ 
  │ 2 import { Store as ExpressStore } from 'express-session';
  │                                         ~~~~~~~~~~~~~~~~~
  │ 
  │ node_modules/.pnpm/@tinyhttp/session@1.0.7/node_modules/@tinyhttp/session/dist/index.d.ts:10:40 - error TS2503: Cannot find namespace 'Express'.
  │ 
  │ 10 export declare class Cookie implements Express.SessionCookie {
  │                                           ~~~~~~~
  │ 
```

I installed it manually and it broke everything. I will double check what it broke exactly but I thought I wouldn't need express types for tinyhttp work??

**To Reproduce**

1. ... use @tinyhttp/session middleware
2. ... add express as dependency

**Expected behavior**

I expected it to run my app fine, however at transpile time it caused it to error.

Any ideas as to what this means I need to do?

**Versions**

* `node`: 14
* `@tinyhttp/app`: 1.0.11
* `@tinyhttp/session`: 1.0.7

**Additional context**

**Comment by talentlessguy** [comment]
Could you try updating please? via

```sh
pnpm i @tinyhttp/session@1.0.8
```

**Comment by talentlessguy** [comment]
Is the problem still present, @creepinson?
