### ISSUE TITLE
App.use does not alter request path for middleware

### ISSUE THREAD

**Issue by ewired** [talentlessguy/tinyhttp#203]
**Describe the bug**

The `sirv` or `serve-static` middleware does not serve files when putting it under another path in the router. It does work when the mount path is `/` or corresponds with the filesystem.

**To Reproduce**

```js
import { App } from "@tinyhttp/app";
import serveStatic from "serve-static";
import sirv from "sirv";

new App()
  .use("/static", sirv("dist/client"))
  .use("/static2", serveStatic("dist/client"))
  .use("/pages", sirv("dist/client"))
  .listen(3000);

```
```sh
$ curl http://localhost:3000/static/pages/index.js
Not found
$ curl http://localhost:3000/static2/pages/index.js
Not found
$ curl http://localhost:3000/pages/index.js
console.log("hi");

```

**Expected behavior**

```
$ curl http://localhost:3000/static/pages/index.js
console.log("hi");
$ curl http://localhost:3000/static2/pages/index.js
console.log("hi");
$ curl http://localhost:3000/pages/index.js
Not found
```

**Versions**

* `node`: v14.13.0
* `@tinyhttp/app`: ^1.0.14

**Additional context**

```
$ tree dist/client
dist/client
└── pages
    ├── index.js
    ├── index.js.map
    ├── outdex.js
    └── outdex.js.map
```

**Comment by talentlessguy** [comment]
interesting, using `epxress` the path gets removed from `req.path`:

```js
import App from 'express'

import serveStatic from "serve-static";
import sirv from "sirv";

App()
  .use("/static", (req, res) => {
        console.log(req.path, req.url)
        sirv("dist/client")(req, res)
    })
  .use("/static2", serveStatic("dist/client"))
  .use("/pages", sirv("dist/client"))
  .listen(3000);
```

```sh
$ node app.mjs
// $ curl http://localhost:3000/static/pages/index.js
/pages/index.js /pages/index.js
```

and the same code with tinyhttp:

```js
import { App } from '@tinyhttp/app'

import serveStatic from "serve-static";
import sirv from "sirv";

new App()
  .use("/static", (req, res) => {
    console.log(req.path, req.url)
    sirv("dist/client")(req, res)
  })
  .use("/static2", serveStatic("dist/client"))
  .use("/pages", sirv("dist/client"))
  .listen(3000);
```

```sh
$ node app.mjs
// $ curl http://localhost:3000/static/pages/index.js
/static/pages/index.js /static/pages/index.js
```

I think the issue comes from `req.path` property but I don't know yet the exact root of the problem

will investigate

**Comment by talentlessguy** [comment]
ok so what express does is that it strips the path, e.g. `/static`, from `req.url` and `req.path`

but it remains in `req.originalUrl`

will fix it in a moment :D

**Comment by talentlessguy** [comment]
Seems like I fixed it (run `pnpm up -L` to update) but it broke everything else (website as example) D:

currently investigating (again)

**Comment by ewired** [comment]
> Seems like I fixed it (run `pnpm up -L` to update) but it broke everything else (website as example) D:
> 
> currently investigating (again)

If you are referring to the Middleware section of the site, I recall that it has been responding with the same error since yesterday.

**Comment by talentlessguy** [comment]
@ewired no I mean this:

```
/favicon.png
First { url: '/favicon.png', orig: '/favicon.png', path: '/favicon.png' }
/favicon.png
/vicon.png
Second { url: '/vicon.png', orig: '/vicon.png', path: '/vicon.png' }
/vicon.png
/png
/png
/png
```

Something bad happens to request... no clue why it happens (yet)

**Comment by talentlessguy** [comment]
okkk i fixed it, this thing didn't work as it should because `req.orignalUrl` contantly got assigned to `req.url` through multiple middleware, resulting in substringing of `req.url`

I suppose it's all working as it should now

try with:

```sh
$ pnpm i @tinyhttp/app@1.0.16
```

**Comment by talentlessguy** [comment]
Looks like it's still not fixed, the example in the issue returns 404 on files

**Comment by ewired** [comment]
I thought it was working for a second, but it turns out it is just forwarding the request on to the `/pages` handler middleware which erroneously corresponds with the filesystem. I've tried some debugging and I can't find what `sirv` and `serve-static` would consider to be wrong about the `req.path`. I have tested `polka` to work correctly in the same example, so it may provide some clues.
```ts
import polka from "polka";
import { logger } from "@tinyhttp/logger";
import serveStatic from "serve-static";
import sirv from "sirv";

polka()
  .use(logger() as any)
  .use("/static", sirv("dist/client"))
  .use("/static2", serveStatic("dist/client"))
  .use("/pages", sirv("dist/client"))
  .listen(3000);
```

```
$ curl http://localhost:3000/static/pages/index.js
console.log("hi");
$ curl http://localhost:3000/static2/pages/index.js
console.log("hi");
$ curl http://localhost:3000/pages/pages/index.js
console.log("hi");
$ curl http://localhost:3000/pages/index.js
Not found
```

**Comment by talentlessguy** [comment]
Just published v1.0.17, seems like it *almost* works the way it should:

```js
import { App } from '@tinyhttp/app'

import serveStatic from "serve-static";
import sirv from "sirv";

new App()
  .use("/static", (req, res) => {
  console.log(req.path, req.url)
    sirv("dist/client")(req, res)
  })
  .use("/static2", serveStatic("dist/client"))
  .use("/pages", sirv("dist/client"))
  .listen(3000);
```

```sh
$ curl http://localhost:3000/static/pages/index.js
console.log('hi')

tinyhttp on  master [$] via ⬢ v15.4.0 
$ curl http://localhost:3000/static2/pages/index.js

tinyhttp on  master [$] via ⬢ v15.4.0 
$ curl http://localhost:3000/pages/pages/index.js
console.log('hi')
```

console:

```
/pages/index.js /pages/index.js
/pages/index.js /pages/index.js
/pages/index.js /pages/index.js
/2/pages/index.js /2/pages/index.js
```

**Comment by talentlessguy** [comment]
I'm happy to finally announce that routing and paths are finally (!!!) fixed

took the whole day to fix multiple bugs but it was worth it

I apologize for not handling this issue before, but now it shouldn't be present anymore.

please update to latest and let me know if it's still present

**Comment by calumk** [comment]
@talentlessguy - I think I am still getting some strange behaviour here, but not 100%.
It could be the way my _routes.js file is setup, but I'm fairly confident.

```
main.js
  └─ public
    └─ assets
        └─ style.css
  └─ private
    └─ _routes.js
```


### Trying to mount two middleware on the same route fails, or provides odd behaviour

The example below, with one `use` and one `get` is fine.
**main.js**
```
app.use('/', serveStatic(path.join(__dirname, 'public/'))); 👍  (eg : /assets/css/style.css)
app.get('/', (req, res) => { res.send('Hello World!'); }); 👍  
```


---

Two `use`, causes the serveStatic to fail (order is unimportant)
**main.js**
```
app.use('/', serveStatic(path.join(__dirname, 'public/')));  👎  
app.use('/', require('./private/_routes.js')) 👍 
```

**routes.js**
```
const tinyHttp = require('@tinyhttp/app');
const app = new tinyHttp.App();
    app.get('/', (req, res) => {
        res.send("Hello World")
    });
module.exports = app;
```

---

It still fails if i shift the serveStatic to a separate path, because the` '/'` seems to takes precedence (order is unimportant)
```
app.use('/assets', serveStatic(path.join(__dirname, 'public/'))); 👎  
app.use('/', require('./private/_routes.js')) 👍 
```

The only solution is to shift the routes to a separate` 'routes'` path too, but now i cant have any reference under the `'/' `path
```
app.use('/assets', serveStatic(path.join(__dirname, 'public/assets'))); 👍  
app.use('/routes', require('./private/_routes.js')) 👍  
```

---
---
---

Now it gets weirder....

In the following example there is nothing specified under '/' - it should return "Not found"
However, it returns "Hello World".

main.js
```
let tinyHttp = require('@tinyhttp/app');
const app = new tinyHttp.App();

let routes = require('./private/_routes.js')
app.use('/', routes);

app.listen(1339, () => console.log(`Listening on http://localhost:1339`))
```

**_routes.js**
```
const tinyHttp = require('@tinyhttp/app');
const app = new tinyHttp.App();
    app.get('/test', (req, res) => {
        res.send("Hello World!")
    });

module.exports = app
```

Dropping the empty '/' solves this issue (but not others mentioned above!)
so : 
`app.use('/', routes); ` - Weird behaviour, 
`app.use(routes); ` - Correct behaviour, 
`app.use('/admin' , routes); ` - Correct behaviour, 



Example Dir for testing is here.
[tinyHttpRoutingError.zip](https://github.com/talentlessguy/tinyhttp/files/5734910/tinyHttpRoutingError.zip)

**Comment by talentlessguy** [comment]
@calumk looks like it's a subapp issue. Subapp handles all the paths starting with `/`, leading to paths in the original apps getting ignored

will close this issue and open a new one
