### ISSUE TITLE
Documentation Error - app.delete

### ISSUE THREAD

**Issue by calumk** [talentlessguy/tinyhttp#204]
**Describe the bug**
code example in Documentation for : [https://tinyhttp.v1rtl.site/docs#appdelete](https://tinyhttp.v1rtl.site/docs#appdelete) is wrong, copied from documentation for app.put

```
app.put('/', (req, res) => {
  res.send(`${req.method || 'PUT'} request to homepage`)
})

```

should read

```
app.delete('/', (req, res) => {
  res.send(`${req.method || 'DELETE'} request to homepage`)
})
```

**Comment by talentlessguy** [comment]
It's fixed now

![image](https://user-images.githubusercontent.com/35937217/102720010-9690ce00-4302-11eb-97ab-4fad92b9879b.png)
