### ISSUE TITLE
res.redirect broken?

### ISSUE THREAD

**Issue by calumk** [talentlessguy/tinyhttp#205]
**Describe the bug**

Path provided to res.redirect gets passed through `encodeURIComponent`, which results in failure, for all but simple redirects.

**To Reproduce**
```
app.get('/test_redirect1', (req, res) => {
  res.redirect('/test_redirect_destination')
});
```
http://localhost:3000/test_redirect1 --> http://localhost:3000/test_redirect_destination 👍 

---
```
app.get('/test_redirect2', (req, res) => {
  res.redirect('/test_redirect_destination/path')
});
```
http://localhost:3000/test_redirect2 --> http://localhost:1338/test_redirect_destination%2Fpath 👎 

---
```
app.get('/test_redirect3', (req, res) => {
  res.redirect('http://example.com')
});
```
http://localhost:3000/test_redirect3 --> http://localhost:1338/http%3A%2F%2Fexample.com 👎 

Cause is probably : 
https://github.com/talentlessguy/tinyhttp/blob/1d6749e2aa6abd4458f09a87f1b5db94cee05977/packages/res/src/headers.ts#L49

**Edit:**
Shouldn't it be `encodeURI` not `encodeURIComponent`

**Comment by talentlessguy** [comment]
It's fixed now.

Install new version:

```sh
pnpm i @tinyhttp/app@1.0.19
```
