### ISSUE TITLE
can you rewrite passportjs with typescript?

### ISSUE THREAD

**Issue by anlexN** [talentlessguy/tinyhttp#206]
**Is your feature request related to a problem? Please describe.**
What problem does it solve?
auth
**Describe the solution you'd like**
[passportjs](https://github.com/jaredhanson/passport) now is es5 syntax, i need modern syntax.

**Comment by talentlessguy** [comment]
Rewriting all libraries in the universe is not the purpose of this project. tinyhttp aims to be a replacement of Express but not the whole ecosystem.

You can start this project yourself (I  mean passport rewrite) and later you can submit a PR with the example of integrating tinyhttp and your passportjs rewrite

**Comment by anlexN** [comment]
@talentlessguy how do you do Auth?

**Comment by talentlessguy** [comment]
@anlexN there are examples of authentification using JWT in the "examples" folder

And you still can use passport, like this:

```js
import passport from 'passport'
```

**Comment by anlexN** [comment]
you don't understand my means. i say what auth solution do you use?

**Comment by talentlessguy** [comment]
@anlexN I use JWT

example is here: https://github.com/talentlessguy/tinyhttp/tree/master/examples/jwt
