### ISSUE TITLE
Subapp overrides all paths, even the ones from original app

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#209]
**Describe the bug**

When a subapp is mounted on a path, all of the middlewares with the same path in the original app are ignored and return 404 because it's being handled by a subapp.

**To Reproduce**

```js
import { App } from '@tinyhttp/app'
import serveStatic from 'serve-static'
import sirv from 'sirv'
import path from 'path'

const app = new App()

const subapp = new App()

subapp.get('/',(req, res) => res.send('hello world'))


app.use('/', sirv('public'))
app.use('/', subapp)

app.listen(3000)
```

```sh
$ curl localhost:3000
hello world
$ curl localhost:3000/hello.txt
Not Found
```

**Expected behavior**

If subapp couldn't find the handler with the request path, the original middleware should handle it instead.

```sh
$ curl localhost:3000
hello world
$ curl localhost:3000/hello.txt
I am a file
```

**Versions**

* `node`: 15.4.0
* `@tinyhttp/app`: 1.1.0

**Additional context**

#203

**Comment by talentlessguy** [comment]
Another noticeable bug is that subapps have incorrect `req.originalUrl` and other URL values

**Comment by talentlessguy** [comment]
@calumk do you have any ideas how to improve subapp handling? In the old version of Polka it used `handler.bind(null, req, res)` but it introduces a lot of bugs

in the new version... I'm not sure what happens here:

```js
super.use(base,
				(req, _, next) => {
					if (typeof base === 'string') {
						let len = base.length;
						base.startsWith('/') || len++;
						req.url = req.url.substring(len) || '/';
						req.path = req.path.substring(len) || '/';
					} else {
						req.url = req.url.replace(base, '') || '/';
						req.path = req.path.replace(base, '') || '/';
					}
					if (req.url.charAt(0) !== '/') {
						req.url = '/' + req.url;
					}
					next();
				},
				fns.map(mount),
				(req, _, next) => {
					req.url = req._parsedUrl.href;
					req.path = req._parsedUrl.pathname;
					next()
				}
			);
		}
```

**Comment by calumk** [comment]
@talentlessguy
Sorry, i'm not going to be much help assisting with this, your expertise in this area far outweighs mine.
It seems i'm good at finding the problems, but I am afraid I am not proficient enough to solve them!

**Comment by calumk** [comment]
@talentlessguy was tinyhttp originally based on polka?

**Comment by talentlessguy** [comment]
@calumk oh no problem then

tinyhttp was inspired by Polka and I took some concepts from it but it doesn't directly depend on Polka

I've spent 2 hours trying to make it work similar to Polka but atm I fail at doing this... but I hope I fix it

So yeah... subapps currently are broken

**Comment by talentlessguy** [comment]
@calumk could you please try to install a new version?

```sh
$ npm i @tinyhttp/app@1.1.1
```

**Comment by calumk** [comment]
@talentlessguy - Thats seems to fix it for me 👍 

Sorry for taking so many hours of your time!

**Comment by talentlessguy** [comment]
@calumk yaaay

and lol you don't have to apologize for me making bugs

thanks for reporting it :D

**Comment by calumk** [comment]
You can add me to the bug contributors list ;)

**Comment by talentlessguy** [comment]
@all-contributors add @calumk for bug
