### ISSUE TITLE
What tinyhttp plans to offer beyond Polka

### ISSUE THREAD

**Issue by paulocoghi** [talentlessguy/tinyhttp#211]
Just out of curiosity, what are the maintainers plan with tinyhttp regarding features and/or performance when comparing to Polka?

Thanks!

**Comment by talentlessguy** [comment]
It's mentioned right in the README and [COMPARISON.md](https://github.com/talentlessguy/tinyhttp/blob/master/COMPARISON.md) file

https://github.com/talentlessguy/tinyhttp#comparison

**Comment by talentlessguy** [comment]
In case you need a more detailed answer:

- tinyhttp provides a list of prebuilt middlewares to avoid using ancient middlewares for express
- tinyhttp offers types out of the box (without having to install custom types)

**Comment by paulocoghi** [comment]
Thanks for the answer!
