### ISSUE TITLE
Can't set multiple cookies with res.cookie 

### ISSUE THREAD

**Issue by I-dodo** [talentlessguy/tinyhttp#215]
**Problem with res.cookie**

I am trying to set multiple cookies with `res.cookie`. 
(Only the last one saved)

My code:
```javascript
const cookieParser = require('@tinyhttp/cookie-parser').cookieParser;
const TinyApp = require('@tinyhttp/app').App;
const app = new TinyApp();

const parse = cookieParser(CookieSecret);
const cookieTime = 1000 * 60 * 60 * 24 * 3;

app.get("/SetInfo", async (req, res) => {
    if(req.query.cookies){
        await new Promise(next => parse(req, res, next));
        res.cookie("name", 1, { httpOnly: true, signed: true, maxAge: cookieTime });
        res.cookie("pass", 1, { httpOnly: true, signed: true, maxAge: cookieTime });

        console.log(req.signedCookies);
        // {pass: 1}
    }
    res.send('ok');
    res.end();
})

app.listen(8080);
```

I tried `@tinyhttp/cookie-parser` and `cookie-parser`, but the same results.

**Versions**

* `node`: 12.19.0
* `@tinyhttp/app`: 1.1.5
* `@tinyhttp/cookie-parser`: 1.1.6

Does someone know what may be the problem?

**Comment by talentlessguy** [comment]
I'm not sure why use `await parse` here when `@tinyhttp/cookie-parser` has a completely different API

the correct way to use it is:

```js
import { cookieParser } from '@tinyhttp/cookie-parser'
import { App } from '@tinyhttp/app'

const app = new App()
app.use(cookieParser('SECRET'))
```

**Comment by I-dodo** [comment]
I am trying to prase the cookies just if specific data is sent with the page. Is there a better way to do it?
(I do it so I can speed up my server as fast as possible)

**Comment by talentlessguy** [comment]
@I-dodo I'm not sure what you mean but in order to use cookieParser do this:

```js
import { App } from '@tinyhttp/app'
import { cookieParser } from '@tinyhttp/cookie-parser'

new App()
  .use(cookieParser())
  .get('/', (req, res) => {
    if (req.headers.cookie) {
    // Cookies that have not been signed
    console.log('Cookies: ', req.cookies)

    // Cookies that have been signed
    console.log('Signed Cookies: ', req.signedCookies)
    }
  })
  .listen(3000)

// curl command that sends an HTTP request with two cookies
// curl http://localhost:3000 --cookie "Cho=Kim;Greet=Hello"
```

**Comment by I-dodo** [comment]
I try to explain myself in another way:
I am trying to `parse`, use and `set` new cookies, only if the client sends specific data.
I do it because most of the URLs in the server do not use cookies and it pointless to do it to every URL the server gets (It burden).

I already do it with the session and it works very well and increases the server speed in 10-15 milliseconds.
I hope it possible to do it with the cookies too.

+I didn't think that the problem was the way I used the `@tinyhttp/cookie-parser`. If there isn't a fast solution, it not critical.

Thank anyway :)

**Comment by talentlessguy** [comment]
@I-dodo ohhh now it's clear

then I recommend using `@tinyhttp/unless` to set `cookieParser(...)` only for specific middleware:

```js
import { App } from '@tinyhttp/app'
import { unless } from '@tinyhttp/unless'
import { cookieParser } from '@tinyhttp/cookie-parser'

const app = new App()

app.use(unless(cookieParser(),  { (req) => req.query.someProp === 'someValue'  })).listen(3000)
```

as for setting cookies, multiple `res.cookie` calls will override the `Set-Cookie` header. And it's surely a bug. Will work on it now.

thanks for reporting :D

**Comment by I-dodo** [comment]
Greate, thanks for the help.
BTW I adore this framework. The speed it Amazing! (～￣▽￣)～

**Comment by talentlessguy** [comment]
Ok i think this is fixed, at least tests pass.

to install:

```sh
pnpm i @tinyhttp/app@1.1.9
```

**Comment by talentlessguy** [comment]
@I-dodo ok I fixed the broken release, should be working now.

also could you please explain why do you use CommonJS instead of `import` / `export` with tinyhttp? ESM is fully supported in tinyhttp but I noticed that some folks keep using cjs... Is it a personal pref?
