### ISSUE TITLE
Feedback ✨

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#216]
This issue serves a purpose of gathering feedback about tinyhttp.

feel free to express your both positive and negative feedback here, what you like about the framework or what you hate in it.

If your project uses tinyhttp you can also write here if you have thoughts about it.

<sub><strong>p.s.</strong> migration from Express feedback is especially welcome</sub>

**Comment by shadowtime2000** [comment]
@talentlessguy You should probably put your repo [in this thread] to get the ability to transfer this issue to a discussion.

**Comment by talentlessguy** [comment]
@shadowtime2000 created a discussion: https://github.com/talentlessguy/tinyhttp/discussions/217
