### ISSUE TITLE
404 when passing more than 1 middleware to app.method

### ISSUE THREAD

**Issue by creepinson** [talentlessguy/tinyhttp#22]
Sooooo, 
I am having a new issue: the first response gives an actual error/result (which is expected), but on the second request it responds with my 404 noMatchHandler.. It doesn't matteer what the url is on the second request, it just sends the 404 and then complains the headers are already sent.

**Comment by talentlessguy** [comment]
@creepinson once again I will need a reproducible demo :)

**Comment by creepinson** [comment]
Oof, I installed the latest version of @tinyhttp/app and got this on almost every page except for /profile....
![image](https://user-images.githubusercontent.com/11761863/87818157-fbf60580-c81e-11ea-9cde-5a6dbd44666d.png)

**Comment by talentlessguy** [comment]
@creepinson interesting, there is some external module made by you. Could you please make a *route-only* demo that I can try?

Also, body-parser doesn't work. See #25

**Comment by talentlessguy** [comment]
@creepinson is it still relevant?

**Comment by talentlessguy** [comment]
I'm not sure if it is still relevant, so closing

feel free to re-open if it persists

**Comment by creepinson** [comment]
Ok, well I'm still getting a 404 error and it seems to be with using multiple middlewares like so:

My "test" middleware:
``ts
async function test(req: Request, res: Response, next?: NextFunction) {
	console.log(`req body: ${JSON.stringify(req.body)}`);
	next!();
}
```

Then I use it like so:
```ts
app.post('/register', test, register);
```

where the test middleware is supposed to be executed and then after it is called my register middleware in the rest of my code gets called. While it does execute the test middleware and prints out the request body, it then gives the following from the logger middleware:
`POST 404 Not Found /register`
even though it just worked with the first test middleware.

 I will try and make a reproducable demo as well.

**Comment by creepinson** [comment]
Ok, I've managed to create a simple demo: https://github.com/creepinson/tinyhttp-example

Output from the demo:
```
Listening on :8080
Req url: "/test"
GET 404 Not Found /test
```

**Comment by creepinson** [comment]
I don't think I can reopen this issue manually, I think you have to do it for me.

**Comment by talentlessguy** [comment]
@creepinson, OK reoping

I won't be able to help ya for ~2 weeks so pls be patient :)

**Comment by talentlessguy** [comment]
Ok, I'm back here

the issue comes from when there are more than 1 wares passed to `app.method`

will look into this very soon

**Comment by talentlessguy** [comment]
@creepinson should be fixed now, in this code:

https://github.com/talentlessguy/tinyhttp/blob/53043780f23a716b2664a71c6b367b2dd0e941ec/packages/app/src/router.ts#L91-L98

please check

**Comment by creepinson** [comment]
seems to be working with my small example :D
I will also try my larger example but I think it might be fixed.
