### ISSUE TITLE
no `preflightContinue` option in @tinyhttp/cors

### ISSUE THREAD

**Issue by calumk** [talentlessguy/tinyhttp#221]
**Describe the bug**
HTTP Methods requiring preflights do not work.

GET / POST work as intended as they are simple requests
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests

Passing a "DELETE" request from postman or similar, also works as intended, as preflight is skipped

**To Reproduce**
Passing a "DELETE" request from fetch (in browser) doesnt work, as it sends a "OPTIONS" Request first.

The only way to get this to work at the moment is to have an empty options route

```
// doesnt work without below!
api.delete('/schemas', async (req, res) => {
  res.send(`thanks for ${JSON.stringify(req.body)}`)
});
```

```
// required to make the above work!
api.options('/schemas', (req, res) => {
  res.send(" ");
});
```

**Comment by calumk** [comment]
Sorry for the short description above, I was in a rush.
Having a look at the express handling for 'OPTIONS', they seem to respond with headers automatically

https://github.com/expressjs/cors/blob/5c0b6c7a0cbf126c949b9a76c7c67e26eba6b3e1/lib/index.js#L159-L190


I'm not sure how best to solve this.

If you modify the route handler, to push  both OPTIONS and DELETE Middleware on a delete request, it solves the issue.
Maybe the OPTIONS middleware can be pushed for all requests? 

https://github.com/talentlessguy/tinyhttp/blob/77e1bd6e39b23d771217917e0c122fe1c45cb8f6/packages/router/src/index.ts#L207

```
    delete(...args) {
        pushMiddleware(this.middleware)({
            path: args[0],
            handler: args[1],
            handlers: args.slice(2),
            method: 'OPTIONS',
            type: 'route'
        });
        pushMiddleware(this.middleware)({
            path: args[0],
            handler: args[1],
            handlers: args.slice(2),
            method: 'DELETE',
            type: 'route'
        });
        return this;
    }
```

**Comment by calumk** [comment]
Ignore Above, Pushing two middlewares does not solve this.

`api.options('/schemas', (req, res) => {  res.send(" "); });`

remains the only working solution for me at the moment

**Comment by talentlessguy** [comment]
Is it an issue with core or `@tinyhttp/cors` module?

**Comment by calumk** [comment]
Not sure im afraid.

I think there is a difference in how express/tiny-http handle this, thats why i linked to the express cors plugin, because they deal with it there

**Comment by talentlessguy** [comment]
Could you please try with `@tinyhttp/cors`?

```js
import { App } from '@tinyhttp/app'
import { cors } from '@tinyhttp/cors'

const app = new App()

app.options('*', cors())

app.use((_, res) => res.send('Regular request'))

app.listen(3000)
```
