### ISSUE TITLE
CORS middleware multiple origin support

### ISSUE THREAD

**Issue by aldy505** [talentlessguy/tinyhttp#224]
Express' cors middleware support multiple origin routes, yet tinyhttp only support a single origin.

I'd like to know if there is any reason/consideration for this. If not, I'll fork the repo and submit a PR for this as soon as possible.

Thanks!

**Comment by talentlessguy** [comment]
multiple origins are supported...

just do this:

```js
cors({ origin: 'example.com,example2.com' })
```

here's where origin gets set https://github.com/talentlessguy/tinyhttp/blob/a909c9918460eeef4e0ed2509399ed7b46149466/packages/cors/src/index.ts#L32

**Comment by talentlessguy** [comment]
interesting.... so cors header doesn't support multiple origins by default

but expressjs/cors does...

https://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains

**Comment by aldy505** [comment]
Alright. I was wondering if is there any bug with the current cors module? I tried with this simple code and it won't load anything.

```js
import { App } from '@tinyhttp/app'
import { cors } from '@tinyhttp/cors'

const app = new App()
app
    .use(cors({origin: '*'}))
    .options('*', cors({origin: '*'}))
    .get('/', (req, res) => {
        res.status(200).json(
            {
                headers: req.headers,
                origin: req.get('origin'),
                rawHeaders: req.rawHeaders,
            }
        )
    })
    .listen(3000, () => {
        console.log("Server started on http://localhost:3000")
    })
```

Also if you emptied the origin option, you'll get this error, which I think this is pretty weird:
```
const { origin = '*', methods = ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'], allowedHeaders, exposedHeaders, credentials, maxAge, optionsSuccessStatus = 204, preflightContinue = false } = opts;
            ^

TypeError: Cannot read property 'origin' of undefined
    at cors (D:\User-Aldy\Archives\XAMPP\lighthttp-test\node_modules\@tinyhttp\cors\dist\index.cjs:11:13)
```

But Express' cors did fine. I'm running Windows on Node 14.15.4, with pnpm 5.16.0.

Aside from that problem, I already wrote on multiple (array) origin and RegExp origin as well. If my error didn't happen on yours, I'll try to test on docker and submit a PR. Thanks!

**Comment by talentlessguy** [comment]
@aldy505 nah I think it's just that it's not implemented in `@tinyhttp/cors` but is implemented in `cors`...

also regarding that bug, could you please try it again v new version?

```sh
pnpm i @tinyhttp/cors@1.1.3
```

**Comment by aldy505** [comment]
I think it was my fault, Express cors defaulted true for `preflightContinue`. May I suggest changing it to true as well? 

I can't think of how to put multiple origin on test folder, so I make one repository on it (with Regex and Array support): https://github.com/aldy505/tinyhttp-cors-test

**Comment by talentlessguy** [comment]
@aldy505 ok, gonna push a new version for defaulting to true

regarding RegExp support, could you please PR this? I'd gladly merge this :>

**Comment by talentlessguy** [comment]
`preflightContinue` defaults to true now, in new version

```sh
pnpm i @tinyhttp/cors@1.1.4
```
