### ISSUE TITLE
CORS: 404 request for all OPTION requests

### ISSUE THREAD

**Issue by tim-field** [talentlessguy/tinyhttp#229]
**Describe the bug**

I get a 404 for OPTIONS requests, that work with GET.

I've tried `preflightContinue: true` that didn't help either

**To Reproduce**

```
app
  .use(cors({origin: '*'}))
  .options('*', cors({origin: '*'}))
  .get('/collection', async (_, res) => {
 ```

**Versions**

* `node`: 14
* `@tinyhttp/cors`: 1.1.5
* `@tinyhttp/app`: 1.1.12

**Comment by talentlessguy** [comment]
@tim-field do you have an idea of how to fix this?

**Comment by aldy505** [comment]
@tim-field can you please try using #231 or through my sample repo here: https://github.com/aldy505/tinyhttp-cors-test

**Comment by talentlessguy** [comment]
@aldy505 should be fixed with the new version:

```sh
pnpm i @tinyhttp/cors@1.1.7
```
