### ISSUE TITLE
Setup Husky pre-commit hook

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#23]

**Comment by RocktimSaikia** [comment]
@talentlessguy Is this issue still open? If it is can I work on it ?

**Comment by talentlessguy** [comment]
@RocktimSaikia yes it is, made this one for myself, but it's ok if you do it.

I want to setup a pre-commit hook that would run a linter and tests before commiting

So we should make a `lint` npm script with `eslint ./**/*/src/*.{ts,js}` (or any other glob to match all ts and js code)

Also make a script to run linter and tests, e.g. `pre-commit` script maybe (any other name would fit)

Then, install husky, and run this script on pre commit

**Comment by RocktimSaikia** [comment]
@talentlessguy Right. I also had the same idea. Currently, it does not have a separate script for linting so I was gonna create the script and add it to the `pre-commit` hook along with the test script. But I was not sure about adding the build scripts so waited for your comment before doing any more work on that

**Comment by RocktimSaikia** [comment]
@talentlessguy For some reason, most of the tests are failing even tho I haven't even changed any of the code yet. Just running the test script alone logs a ton of failing tests. Also, I did follow [the installation guide](https://github.com/talentlessguy/tinyhttp/blob/master/CONTRIBUTING.md) provided here so not sure what's causing the tests to fail. Can you tell what might be causing these errors ?

![Screenshot_15](https://user-images.githubusercontent.com/33410545/91466969-849ba300-e8ad-11ea-8205-c387f4b141a5.png)

**Comment by talentlessguy** [comment]
@RocktimSaikia the reason why tests fail is that I need to update the contributing guide...

try running `pnpm i -r` and `pnpm build -r`, these should work

**Comment by RocktimSaikia** [comment]
@talentlessguy  I already tried all of the command solutions. But still the same. Do I need to specifically set some env file configs to run it locally? I think some of the packages are not building upon running the build command. Probably that's why It can't find `its corresponding type declarations` !! 

![Screenshot_1](https://user-images.githubusercontent.com/33410545/91490127-92fab680-e8cf-11ea-84d4-b0ff6c21883d.png)

**Comment by talentlessguy** [comment]
@RocktimSaikia try reloading TS Server (Ctrl + Shift + P -> Reload TS Server) in VS Code

**Comment by talentlessguy** [comment]
Closed with #53 :rocket:
