### ISSUE TITLE
Websockets example app

### ISSUE THREAD

**Issue by RikuVan** [talentlessguy/tinyhttp#236]
Trying to set up websockets with tinyhttp and, e.g., socket.io and there was a bit of friction because of a missing example. Would be willing to make a PR with an example app but first I need to check what is the best way to do it. This seems to work but is there a preferable way?

```js
import {Server, Socket} from 'socket.io'
import {App} from '@tinyhttp/app'
import http from 'http'

const app = new App()

const server = http.createServer()
server.on('request', app.attach)

const io = new Server(server)

io.on('connection', (socket: Socket) => {
	console.log('connected')
})

server.listen(5000, () => console.log('Started on http://localhost:5000'))
```

**Comment by talentlessguy** [comment]
socket.io is a bit of old

might worth making an example w/ [ws](npm.im/ws) pkg instead

**Comment by RikuVan** [comment]
Sure I can use ws (had chosen socket.io for the rooms functionality I need for my case). I wonder then if the better to set it up with tinyhttp is using the `upgrade` event and `app.listen` like this: [https://github.com/websockets/ws#multiple-servers-sharing-a-single-https-server](https://github.com/websockets/ws#multiple-servers-sharing-a-single-https-server)?

**Comment by talentlessguy** [comment]
@RikuVan `app.listen` returns the server so you can use it like this:

```js
const server = app.listen(...)

server.on('...', ...)
```

**Comment by talentlessguy** [comment]
due to tinyhttp being an HTTP framework I don't think there's that much sense in this issue

any way would be preferrable, although there''s no any wrapper around tinyhttp for ws yet

**Comment by talentlessguy** [comment]
@RikuVan I just have published a library [tinyws](https://github.com/talentlessguy/tinyws)

u can use it like this:

```js
import { App, Request } from '@tinyhttp/app'
import { tinyws, TinyWSRequest } from 'tinyws'

const app = new App<any, Request & TinyWSRequest>()

app.use(tinyws())

app.use('/ws', async (req, res) => {
  if (req.ws) {
    const ws = await req.ws()

    return ws.send('hello there')
  } else {
    res.send('Hello from HTTP!')
  }
})

app.listen(3000)
```
