### ISSUE TITLE
Implicit HEAD support

### ISSUE THREAD

**Issue by sonnyp** [talentlessguy/tinyhttp#243]
I'm not entirely sure if it's a bug or a feature request.

**Describe the bug**

`GET` routes do not have implicit support for `HEAD` requests.

Most (all?) http frameworks out there have implicit `HEAD` requests for `GET` routes, they will simply ignore the response body.
Also, `app.head` is not documented which makes it difficult to workaround.

My opinion is that if a `GET` route doesn't have an associated `HEAD` route, support should be implicit.

**To Reproduce**

```js
import {App} from '@tinyhttp/app';

const app = new App();

function ping(req, res) {
  res.statusCode = 204;
  res.end();
}
// app.head('/ping', ping); // workaround
app.get('/ping', ping);

app.listen(3000);
```

```sh
curl -v -X HEAD http://localhost:3000/ping # -> 404 not found
```

**Expected behavior**

```sh
curl -v -X HEAD http://localhost:3000/ping # -> 204
```

**Versions**

* `node`: 14
* `@tinyhttp/app`: 1.2.20

**Comment by talentlessguy** [comment]
you should use `res.send` for it to work properly

`res.end` is a built-in method that doesn't do anything, that's why 404 is returned

**Comment by sonnyp** [comment]
It's the same problem with `res.send`

```
import {App} from '@tinyhttp/app';

const app = new App();

function ping(req, res) {
  res.statusCode = 204;
  res.end();
}
// app.head('/ping', ping); // workaround
app.get('/ping', ping);

app.listen(3000);
```

Of course Node.js `res.end` does something https://nodejs.org/api/http.html#http_response_end_data_encoding_callback

**Comment by sonnyp** [comment]
looks like `res.send` does support `HEAD` https://github.com/talentlessguy/tinyhttp/blob/master/packages/send/src/send.ts#L56

However a `app.get` route is simply not registered for HEAD. The handler isn't even called.

**Comment by talentlessguy** [comment]
@sonnyp hmm probably I need to add a check for `req.method` in `app.handle`

**Comment by talentlessguy** [comment]
I need to think how to edit `find` func in a way that I don't have to query the mw twice...
