### ISSUE TITLE
Participating to a benchmark

### ISSUE THREAD

**Issue by waghanza** [talentlessguy/tinyhttp#246]
Hi,

I lead a project (https://github.com/the-benchmarker/web-frameworks) that aims to be a simple benchmark between various of frameworks.

Do you which to participate ?

Regards,

**Comment by talentlessguy** [comment]
hi

i wouldn't mind my framework to be there

should i assign u to this issue so u add tinyhttp?

**Comment by waghanza** [comment]
will do ❤️ and ping you to review

**Comment by talentlessguy** [comment]
Closing since it's merged
