### ISSUE TITLE
Add comparison with fastify and document tradeoffs 

### ISSUE THREAD

**Issue by tzvipm** [talentlessguy/tinyhttp#247]
**Is your feature request related to a problem? Please describe.**
What problem does it solve?

It seems unfair to boast 2x improvement over express and compare with polka, but not fastify whose benchmarks show >3x improvement over express.

**Describe the solution you'd like**

1. Add a comparison with fastify to COMPARISSON.md
2. Document why someone would chose tinyhttp over a faster alternative like fastify.

**Describe alternatives you've considered**

**Additional context**

https://github.com/fastify/fastify#benchmarks

**Comment by talentlessguy** [comment]
see: https://github.com/talentlessguy/tinyhttp#benchmarks

the reason why Fastify isn't mentioned anywhere is because it's API differs from Express.

tinyhttp is Express-like framework. that's why I compare to Polka and Express
