### ISSUE TITLE
Express body-parser doesn't parse the body

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#25]
**Describe the bug**

With using Express `body-parser`, neither `bodyParser.json` nor `bodyParser.urlencoded` work. Instead of a body will with data we get `{}`

**To Reproduce**

```ts
import { App } from '@tinyhttp/app'
import bodyParser from 'body-parser'

const app = new App()

app.use(bodyParser.urlencoded({ extended: false }))

// parse application/json

app.use(bodyParser.json())

app.use(function (req, res) {

  res.setHeader('Content-Type', 'text/plain')
  res.write('you posted:\n')
  res.end(JSON.stringify(req.body, null, 2))

})

app.listen(3000)
```

and then in terminal:

```sh
curl localhost:3000 -X POST -F "a=b"
```

**Expected behavior**

`req.body` would be filled with data

**Versions**

* `node`: 14.5.0
* `@tinyhttp`: 0.2.12

**Additional context**

[body-parser repo](https://github.com/expressjs/body-parser)

**Comment by talentlessguy** [comment]
Temporary workaround: using [parsec](https://github.com/talentlessguy/parsec)

**Comment by talentlessguy** [comment]
After some magic happening, it now works:

```ts
import { App } from '@tinyhttp/app'
import bodyParser from 'body-parser'

const app = new App()

app.use(bodyParser.urlencoded({ extended: false }))

app.use((req, res, next) => {
    console.log(req.body)
    next()
})

app.get('/', (req, res) => void res.send(req.body))

app.listen(3000)
```

**Comment by spideythewebhead** [comment]
Hi, i tried to use body parser with tinyhttp (using typescript) but it doesnt seem to work due to types

**Comment by talentlessguy** [comment]
@spideythewebhead please provide a reproduction sample

**Comment by spideythewebhead** [comment]
Holy shit you answered fast :p

```
import { App } from "@tinyhttp/app";
import { logger } from "@tinyhttp/logger";
import bodyParser from "body-parser";

export const server = new App();

server.use(bodyParser.json());
```

![Screenshot 2021-02-17 at 10 57 01 PM](https://user-images.githubusercontent.com/55633618/108267003-78fdaa80-7173-11eb-987d-a58175395246.png)

**Comment by spideythewebhead** [comment]
ok, a 'workaround' is to cast as `any` and seems to work fine!

```
server.use(bodyParser.json() as any);
server.use(bodyParser.urlencoded() as any);
```

Sorry, for the inconvenience.

**Comment by talentlessguy** [comment]
@spideythewebhead that's not a good solution

could you pls provide your tinyhttp version? I thought that type error got fixed before

**Comment by spideythewebhead** [comment]
@talentlessguy yeah i know but its not a great deal

```
"@tinyhttp/app": "^1.1.12",
"body-parser": "^1.19.0"
```

**Comment by spideythewebhead** [comment]
Ok I am not sure what exactly happened, I did try it on a new project and it works without the casting

**Comment by iamricard** [comment]
Hi! I've run into this, and it seems to still be happening. `body-parser@1.19.0` (same for `@types`) and `@tinyhttp/app@1.1.12`. It looks like `SyncHandler` and `AsyncHandler` claim that `next?: NextFunction` is nullable, but `body-parser` types expect it to always be present `export type NextHandleFunction = (req: IncomingMessage, res: http.ServerResponse, next: NextFunction) => void;`.

**Comment by talentlessguy** [comment]
@iamricard Cannot reproduce this, `body-parser` here even with installed types works:

https://github.com/talentlessguy/tinyhttp/commit/e8bc0942ceb70def1fa516dd349c6a2766d63bed
