### ISSUE TITLE
Can I auto-generate the API documentation?

### ISSUE THREAD

**Issue by harshmandan** [talentlessguy/tinyhttp#253]
There's a feature in Fastify, which lets you use swagger to auto-generate the documentation.
Can I do the same in tiny-http as well?

**Comment by talentlessguy** [comment]
tinyhttp is similar to express

so (almost) anything for express will work for tinyhttp

https://github.com/scottie1984/swagger-ui-express

**Comment by harshmandan** [comment]
thanks for the quick reply!
Okay, I'll try integrating this once.

**Comment by talentlessguy** [comment]
I've also tried with [openapi-validator-middleware](https://github.com/PayU/openapi-validator-middleware), probably should work with it as well
