### ISSUE TITLE
Use a logging library as a logger implementation instead of console.log

### ISSUE THREAD

**Issue by Arnovsky** [talentlessguy/tinyhttp#38]
**Is your feature request related to a problem? Please describe.**
I feel that using something like `pino` or `winston` will be best for logging purposes, since there is no need to create our own logger and reinvent the wheel.

**Describe the solution you'd like**
Rewrite the current logger package to use a fully-featured logging library.

**Describe alternatives you've considered**
Using `console.log` has disadvantages, some users would like to save the logs to a file, log via http, etc... This is not possible using our current logging solution.

**Comment by talentlessguy** [comment]
We could add an option called `output` which would be a function that accepts only one arg, like this:

```ts
logger({ output: console.log })
```

or like this:

```
logger({ output: async (x) => await writeFile('my-log.txt', x) })
```

and then in the logger:

```ts
options.output(x)
```

About re-inventing the wheel. That was the point. `@tinyhttp/logger` is a basic logger that will fit to most cases, but for something advanced it's recommended to use Pino. It's written in the readme. We can add the `output` option - but I'm not sure if it should be as full featured as Pino.

**Comment by Arnovsky** [comment]
Cool, I'll make a PR.

**Comment by talentlessguy** [comment]
@Arnovsky nice, looking forward to it
