### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#47]
tinyhttp offers a list of pre-made middleware, to ease maintainability and provide better compatability and types.

Here will be a full list of middlewares to be implemented:

- [x] logger
- [x] static
- [x] markdown
- [x] cors
- [x] jwt
- [x] cookie-parser
- [x] [body parser](https://github.com/talentlessguy/parsec)
- [x] session
- [x] ip-filter
- [x] favicon
- [x] ping (response time metric + setting `X-Response-Time` header)
- [x] bot-detector (using something like [this](https://github.com/gorangajic/isbot))
- [x] unless (#118) 
- [x] dotenv (load dotenv from root or specified file)
- [x] rate-limit (#96)
- [x] pug
- [x] jsonp

If you want to implement any and have questions, write down to the thread

**Comment by talentlessguy** [comment]
# Short descriptions of all of the to-be-implemented modules

## `@tinyhttp/graphql`

GraphQL API Server, same as [express-graphql](https://github.com/graphql/express-graphql) (we can add / remove  features though)

## `@tinyhttp/apollo`

GraphQL Apollo Server,  similar to [apollo-server-express](https://github.com/apollographql/apollo-server)

## `@tinyhttp/session`

Simple session middleware, similar to [express-session](https://github.com/expressjs/session)

## `@tinyhttp/xml-body`

Just a plain simple `await once(req, 'data').then(x => stuff(x))` (like [parsec]()) but with XML only parsing. Sends 400 if failed to parse.

## `@tinyhttp/server-push`

HTTP/2 server push for tinyhttp. I didn't find any good middleware for Koa or Express to copy from, so u have to come up with ur own ideas :D

## `@tinyhttp/ip-filter`

IP filtering middleware that sends 403 if it matches the filter.
Something like:

```ts
app.use(filter({ filter: '(*.)?example.com', forbidden: '403 Go away' })).use((req, res) => void res.send(`Hello not example.com!`)
```

Will accept  `filter` (request to send 403 to), `forbidden` (custom message), `id` (custom id, defaults to `req.ip` as options.

Similar to [koa-ip-filter](https://github.com/tunnckoCore/koa-ip-filter)

more descriptions coming soon...

**Comment by creepinson** [comment]
I would like to see session implemented, so I might try doing it myself. Also, is there any support for view engines like EJS or PUG?

**Comment by talentlessguy** [comment]
@creepinson good luck with the session middleware!

for template engines, see https://github.com/talentlessguy/tinyhttp/issues/7

**Comment by creepinson** [comment]
I never really finished writing the session middleware - so don't count on me to finish it. I might still try though.

**Comment by talentlessguy** [comment]
@creepinson for rate limiting, gonna add

for session middleware - it's ok I'll either implement it myself or ask someone else

**Comment by talentlessguy** [comment]
@creepinson `@tinyhttp/session` is available now

**Comment by talentlessguy** [comment]
Finally, the list is completed :tada:  All middlewares in the list are implemented! 

Huge thanks to @creepinson, @Luiginator  and @shzmr for helping to achieve this goal :DDD
