### ISSUE TITLE
[Feature] Precompressed static content

### ISSUE THREAD

**Issue by tracker1** [talentlessguy/tinyhttp#48]
Reduce transmission overhead by delivering precompressed (gz/br) versions of static content when the request header indicates support

Expand the static middleware to support serving pre-compressed files with the appropriate headers.

**Comment by talentlessguy** [comment]
Ohh hello there

I added 'gzip' and 'brotli' middlewares to the list of stuff to implement

but extending static server sounds interesting

Could you please show any existing static servers (that can be used as middleware) supporting them?

I thought that making custom static servers with compression would make more sense

e.g. this:

```ts
app.use(gzip({ dist: 'compressed' }))
app.use(staticHandler('compressed')
```

**Comment by tracker1** [comment]
IIRC, koa's static module will look at the Accept-Encoding request header[1] and will use that to see if br or gzip are set... then for whatever the static resource is, if there's a file matching NAME.gz or NAME.br it will send that with the `Content-Encoding` response header set to `br` or `gzip` respectively and the length set to the pre-compressed content.

It should probably be in the box with static, enabled by default, but options to disable the feature(s).  Should probably favor brotli if both are supported by the request since it's usually smaller.

1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding

**Comment by talentlessguy** [comment]
@tracker1 interesting, will look into this soon

**Comment by talentlessguy** [comment]
yo, I decided to remove the static package because it requires too much work outside of the framework,

and alternatives are [shown here](https://tinyhttp.v1rtl.site/learn#static-server)
