### ISSUE TITLE
[Feature] @tinyhttp/static - Support for client-caching requests

### ISSUE THREAD

**Issue by tracker1** [talentlessguy/tinyhttp#49]
A middleware to be used with static that would support for if-modified-since header with a 304 response

This middleware should also support the use of E-Tags

This should be based on a non-pre-compressed file's details.

**Comment by talentlessguy** [comment]
Hmmm could you please show anything like this for Express / Koa / Fastify?

Want to explore how other folks implemented this

Also, PRs welcome 👍

**Comment by Arnovsky** [comment]
@talentlessguy Don't think this should be a new middleware, IMO this needs to be baked in the `static` package.

**Comment by talentlessguy** [comment]
@Arnovsky interesting, we could add an option `caching` that defaults to `true` and sets all proper headers

**Comment by Arnovsky** [comment]
@talentlessguy is there any scenario where you don't want to cache static files?

**Comment by talentlessguy** [comment]
@Arnovsky probably while doing site development when u want the cache to be turned off completely

**Comment by Arnovsky** [comment]
@talentlessguy I don't think that's a valid use-case (since you could just force refresh the browser), but I have looked into other framework implementations, and they allow it to be optionally disabled.

**Comment by talentlessguy** [comment]
@Arnovsky hmmm ok then better have it as an option *just in case*

feel free to PR to add a new property :D

**Comment by talentlessguy** [comment]
yo, I decided to remove the static package because it requires too much work outside of the framework,

and alternatives are [shown here](https://tinyhttp.v1rtl.site/learn#static-server)
