### ISSUE TITLE
Add badges option to @tinyhttp/logger

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#51]
**Is your feature request related to a problem? Please describe.**

It adds emoji badges for better readability

**Describe the solution you'd like**

Add `badges` setting with 2 sub-settings to be used like this:

```js
app.use(logger({ badges: { emoji: true, captions: false }))
```

Default values are both false - if `badges: true` - only toggle emoji. if an object is present - check for the settings.

first setting toggles emoji badges, like this :warning:
second enables emoji alt text (in case emoji fails to display or just prefer the text instead), like this: `warning`

here's a table of emoji / texts:

| emoji | text | status code |
|-----|-------|----------------|
|  :x: | Error  | 500 |
| :warning: | status message | 4XX (Except 404) |
| :ok: | OK | 2XX |
| :mag_right:  | Not Found | 404 |

Should be logged in the beginning:

```
🆗 GET 200 OK /css/shared.css
```

**Additional context**

[Zoya](https://github.com/WoLfulus/zoya) logger that has emoji:

![image](https://user-images.githubusercontent.com/35937217/90548320-7060f300-e195-11ea-9df5-f4abb2b63d7e.png)

**Comment by ahmad-reza619** [comment]
Hi there @talentlessguy , i would like to try these on, is this mean to create a new type of middleware?

**Comment by talentlessguy** [comment]
@ahmad-reza619 hello, nope, as labeled on the issue, it should be done inside `@tinyhttp/logger`

I have a mistake in the original code that leads to confusion, my bad

**Comment by ahmad-reza619** [comment]
I'm sorry for not noticing the label 😅

**Comment by talentlessguy** [comment]
@ahmad-reza619 it's fine, you can make a PR at any time you want, and the setup instructions for this repo are in CONTRIBUTING.md file

let me know if you have any questions and don't be afraid to ask them here

**Comment by ahmad-reza619** [comment]
@talentlessguy what about 3XX status code?

**Comment by ahmad-reza619** [comment]
and also, for captions what should be logged? the status or emoji name?

**Comment by talentlessguy** [comment]
> @talentlessguy what about 3XX status code?

not sure which emoji to pick, will write back here latter

**Comment by talentlessguy** [comment]
> and also, for captions what should be logged? the status or emoji name?
> because you were saying
> 
> > second enables emoji alt text (in case emoji fails to display or just prefer the text instead), like this: warning
> 
> but the tables didn't have any text like `warning`

I meant alt text for emoji symbols, it can be found on Emojipedia

**Comment by talentlessguy** [comment]
@ahmad-reza619 pardon for changing requiremenets, I think instead of coming up with our own emojis (and having to think which ones suit better) we better use this module:

https://github.com/bendrucker/http-status-emojis/blob/master/index.js

**Comment by ahmad-reza619** [comment]
@talentlessguy what about the alt text?

**Comment by talentlessguy** [comment]
@talentlessguy tbh I'm not sure about that we need it now... maybe it's useless?

I mean something like

```
500 bomb GET /
```

doesn't make much sense

probably not worth adding it, just the emoji then

**Comment by talentlessguy** [comment]
@all-contributors please add ahmad-reza619 for code
