### ISSUE TITLE
Optimize the overall site for mobile view.

### ISSUE THREAD

**Issue by RocktimSaikia** [talentlessguy/tinyhttp#54]
**Describe the bug**

Most of the current pages of the site are not responsive. It can be said that no one actually gonna read API docs in mobile but making the site at least responsive is quite important.

**Add any other context about the problem here.**

![Screenshot_3](https://user-images.githubusercontent.com/33410545/91579022-a148e100-e968-11ea-837e-7038f9d6adf0.png)

**Comment by talentlessguy** [comment]
Yeah, didn't have time to make it responsive, will spend some to make it look good on phones

in case you want to work on it, you need to go to `site` folder and run `pnpm i -D @tinyhttp/app` there (to trigger `pnpm` to install packages)

and then go to `static/styles/home.css` and write media queries for mobile

**Comment by RocktimSaikia** [comment]
@talentlessguy Yeah I am working on it.

**Comment by talentlessguy** [comment]
Closed with #57
