### ISSUE TITLE
[middleware] @tinyhttp/static resursive prop doesn't work

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#8]
**Describe the bug**

`recursive` prop doesn't make anything _recursive_. It still has 1-level depth. Should have max depth instead, with handling all the routes properly, e.g. `static/dir/file.js => /dir/file.js`

**Versions**

* `node`: 14.5.0
* `@tinyhttp/app`:  0.2.1

The bug seems to be very easy to fix, so PRs are welcome

**Comment by talentlessguy** [comment]
yo, I decided to remove the static package because it requires too much work outside of the framework,

and alternatives are [shown here](https://tinyhttp.v1rtl.site/learn#static-server)

**Comment by acrodrig** [comment]
If you ever change your mind, it would be nice to have a vanilla static middleware as part of the server. Reasons:

1. It provides parity with other frameworks that have this basic functionality out of the box
2. It is a pain to be researching/fetching/updating/type-ing additional packages around

I have `npm`-fatigue as it is :)

**Comment by talentlessguy** [comment]
@acrodrig this won't be revisited as `sirv` and `serve-handler` both do the job better
