### ISSUE TITLE
Improve website SEO

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#84]
Improve OpenGraph / other meta tags in the website for better search

**Comment by ShashankAgarwal77** [comment]
Hi, Can you assign this task to me?

**Comment by ShashankAgarwal77** [comment]
please reply this comment so I can understand this repo is active

**Comment by talentlessguy** [comment]
@ShashankAgarwal77 this repo is definitely active, check the last commit date

and yes I can assign it to you

**Comment by talentlessguy** [comment]
@ShashankAgarwal77 are you still working on it? (not in a hurry just asking how it's going)
