### ISSUE TITLE
Heroku don't work with tinyhttp

### ISSUE THREAD

**Issue by mhmda-83** [talentlessguy/tinyhttp#85]
**Describe the bug**

I write a simple web service using tinyhttp and i decided to deploy on heroku.
but guess what, heroku don't compatible with tinyhttp.
when i replaced tinyhttp with express, everything works fine.

**To Reproduce**

1. write webservice
2. add Procfile
3. set web: yarn start
4. git add -A
5. git push heroku master

**Expected behavior**

Working Fin!

**Versions**

* `node`: 14
* `@tinyhttp/app`: 0.4.1

**Additional context**

**Comment by talentlessguy** [comment]
how exactly it "doesn't  work"? are there any errors showing up?

**Comment by mhmda-83** [comment]
> how exactly it "doesn't work"? are there any errors showing up?
Application crashed with this log:
Error R10 -> Web process failed to bind to $PORT within 60 seconds of launch

**Comment by mhmda-83** [comment]
> how exactly it "doesn't work"? are there any errors showing up?

Application crashed with this log:
Error R10 -> Web process failed to bind to $PORT within 60 seconds of launch

**Comment by talentlessguy** [comment]
> > how exactly it "doesn't work"? are there any errors showing up?
> 
> Application crashed with this log:
> Error R10 -> Web process failed to bind to $PORT within 60 seconds of launch

hmmm strange

may I see how the app looks like (I mean code)

**Comment by mhmda-83** [comment]
```javascript
import { App } from '@tinyhttp/app';
import { logger } from '@tinyhttp/logger';
import fetch from 'node-fetch';
import cheerio from 'cheerio';
import rateLimit from 'express-rate-limit';

const app = new App();

app.use(logger());
app.use(
  rateLimit({
    windowMs: 1000 * 30,
    max: 15,
    handler: (req, res) => {
      res.json({ message: 'Too Many Requests' });
    },
  })
);

app.get('/api/stats', async (_, res) => {
  const rawResponse = await fetch(
    'https://www.worldometers.info/coronavirus/country/iran/'
  );
  const textResponse = await rawResponse.text();
  const $ = cheerio.load(textResponse);

  const totalStats = $('#maincounter-wrap > div > span');

  const totalCases = $(totalStats[0]).text().trimEnd();
  const totalDeaths = $(totalStats[1]).text().trimEnd();
  const totalRecovered = $(totalStats[2]).text().trimEnd();

  const today = new Date();
  const todayFormatted = `${today.getFullYear()}-${
    today.getMonth() + 1 < 10
      ? '0' + (today.getMonth() + 1)
      : today.getMonth() + 1
  }-${today.getDate()}`;
  const newStats = $(`#newsdate${todayFormatted} > div > div > ul > li`)
    .text()
    .match(/\d+[a-zA-Z,0-9]*/g);

  const newCases = newStats[0];
  const newDeaths = newStats[1];

  res.json({ totalCases, totalDeaths, totalRecovered, newCases, newDeaths });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server started on port ${PORT}`);
});
```

**Comment by talentlessguy** [comment]
@mhmda-83 interesting.... still don't know what's causing it because the code looks fine, will reproduce it later today / tomorrow and investigate the issue

sorry that it doesn't work now :c

i'll do my best to fix it asap

**Comment by talentlessguy** [comment]
one my thought is that you maybe forgot to parse the port number, try doing `process.env.PORT ? parseInt(process.env.PORT) : 3000`

**Comment by mhmda-83** [comment]
Still not working.

**Comment by talentlessguy** [comment]
then please wait till i reproduce it :o

**Comment by BRA1L0R** [comment]
@mhmda-83 what port are you currently using?

**Comment by talentlessguy** [comment]
My friend helped me to find out the bug. tinyhttp binds to localhost by default, while it must bind to 0.0.0.0

bugfix is to be released soon :D

**Comment by talentlessguy** [comment]
@mhmda-83 upgrade your deps, it should be working now

**Comment by mhmda-83** [comment]
> @mhmda-83 upgrade your deps, it should be working now

Wow, such a fast fix :)
I test it and it works.

**Comment by talentlessguy** [comment]
@mhmda-83 glad to hear this :smile:
