### ISSUE TITLE
Typescript example doesn't send responses

### ISSUE THREAD

**Issue by creativiii** [talentlessguy/tinyhttp#90]
**Describe the bug**

I'm just getting started with tinyhttp so I may be misunderstanding something, but here goes.

I copied the [typescript example](https://github.com/talentlessguy/tinyhttp/tree/master/examples/typescript), changed the `package.json` to include `"@tinyhttp/app": "0.4.7"` to get it to work with npm.

After installing and starting I get the `Started on http://localhost:3000` message in the terminal, but visiting localhost:3000 doesn't output anything.

Does tinyhttp require `pnpm` or is it just a suggestion?

**To Reproduce**

1. Copy https://github.com/talentlessguy/tinyhttp/tree/master/examples/typescript
2. Remove existing `@tinyhttp/app` dependency and install your own with npm
3. `npm run start`
4. Visit `localhost:3000`

**Expected behavior**

`<h1>Hello World</h1>` should be sent a response, but nothing is and the site just times out.

**Versions**

* `node`: v12.18.2
* `@tinyhttp/app`: 0.4.7

**Comment by talentlessguy** [comment]
very strange, will check it tomorrow

**Comment by talentlessguy** [comment]
@creativiii can't seem to reproduce it, works fine for me:

```
/tmp/app via ⬢ v12.18.2 
➜ ts-node app.ts 
Started on http://localhost:4444
```

![image](https://user-images.githubusercontent.com/35937217/94744190-346aa180-0381-11eb-8efe-cd0bf29c966d.png)

the package.json file:

```json
{
    "dependencies": {
        "@tinyhttp/app": "^0.4.7"
    },
    "devDependencies": {
        "ts-node": "^9.0.0",
        "typescript": "^4.0.3"
    }
}
```

**Comment by talentlessguy** [comment]
Could you show your files pls? package.json and the code

**Comment by creativiii** [comment]
> @creativiii can't seem to reproduce it, works fine for me:
> 
> ```
> /tmp/app via ⬢ v12.18.2 
> ➜ ts-node app.ts 
> Started on http://localhost:4444
> ```
> 
> ![image](https://user-images.githubusercontent.com/35937217/94744190-346aa180-0381-11eb-8efe-cd0bf29c966d.png)
> 
> the package.json file:
> 
> ```json
> {
>     "dependencies": {
>         "@tinyhttp/app": "^0.4.7"
>     },
>     "devDependencies": {
>         "ts-node": "^9.0.0",
>         "typescript": "^4.0.3"
>     }
> }
> ```

That's really strange, could it be caused by WSL?

I'll try with Linux tomorrow

**Comment by talentlessguy** [comment]
> > @creativiii can't seem to reproduce it, works fine for me:
> > ```
> > /tmp/app via ⬢ v12.18.2 
> > ➜ ts-node app.ts 
> > Started on http://localhost:4444
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/35937217/94744190-346aa180-0381-11eb-8efe-cd0bf29c966d.png)
> > the package.json file:
> > ```json
> > {
> >     "dependencies": {
> >         "@tinyhttp/app": "^0.4.7"
> >     },
> >     "devDependencies": {
> >         "ts-node": "^9.0.0",
> >         "typescript": "^4.0.3"
> >     }
> > }
> > ```
> 
> That's really strange, could it be caused by WSL?
> 
> I'll try with Linux tomorrow

ahhhh you're on WSL

then yes most likely it's the WSL issue, you need to tweak it probably

**Comment by creativiii** [comment]
> > > @creativiii can't seem to reproduce it, works fine for me:
> > > ```
> > > /tmp/app via ⬢ v12.18.2 
> > > ➜ ts-node app.ts 
> > > Started on http://localhost:4444
> > > ```
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/35937217/94744190-346aa180-0381-11eb-8efe-cd0bf29c966d.png)
> > > the package.json file:
> > > ```json
> > > {
> > >     "dependencies": {
> > >         "@tinyhttp/app": "^0.4.7"
> > >     },
> > >     "devDependencies": {
> > >         "ts-node": "^9.0.0",
> > >         "typescript": "^4.0.3"
> > >     }
> > > }
> > > ```
> > 
> > That's really strange, could it be caused by WSL?
> > 
> > I'll try with Linux tomorrow
> 
> ahhhh you're on WSL
> 
> then yes most likely it's the WSL issue, you need to tweak it probably

😭

Right guess I know what I'm doing this weekend. I'll update here if I figure it out.

**Comment by talentlessguy** [comment]
closing.....
