### ISSUE TITLE
Add Svelte (or Sapper) SSR example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#93]
Svelte SSR Example (w/ pure `http`): https://github.com/Rich-Harris/svelte-ssr-bundle

Sapper can also be used, here are the docs for it: https://sapper.svelte.dev/docs

To get started with contributing an example, check the [CONTRIBUTING.md](https://github.com/talentlessguy/tinyhttp/blob/master/CONTRIBUTING.md#adding-new-example) file

**Comment by Deadik** [comment]
I'm interested, could you assign me?

**Comment by talentlessguy** [comment]
@Deadik yep, sure :)

**Comment by talentlessguy** [comment]
Closed via #135
