### ISSUE TITLE
Add Prisma example

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#95]
Feel free to submit any kinds of an example with using Prisma and tinyhttp together for a REST API.

## Useful links

Prisma + Express example: https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-express

Prisma docs: https://www.prisma.io/docs/understand-prisma/prisma-in-your-stack/rest

**Comment by Luiginator** [comment]
@talentlessguy Could you assign this issue to me please?

**Comment by talentlessguy** [comment]
@Luiginator yup

**Comment by talentlessguy** [comment]
Closed with #101
