### ISSUE TITLE
Create @tinyhttp/rate-limit

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#96]
`@tinyhttp/rate-limit` is going to be a rate limiting middleware, similar to [express-rate-limit](https://github.com/nfriedly/express-rate-limit)

To get started with creating a new middleware, check the [contributing guidelines for new middleware]()

Before PRing don't forget to:

- write the module itself
- make a proper README with API docs
- write tests with at least ~60% coverage for your module

## Useful links

- [express-rate-limit](https://github.com/nfriedly/express-rate-limit)
- [node-rate-limiter](https://github.com/jhurliman/node-rate-limiter)
- [node-rate-limiter-flexible](https://github.com/animir/node-rate-limiter-flexible)
- [node-ratelimiter](https://github.com/tj/node-ratelimiter)

**Comment by Luiginator** [comment]
@talentlessguy Could you assign this issue to me please?

**Comment by talentlessguy** [comment]
@Luiginator yup

**Comment by talentlessguy** [comment]
Closed with #110
